### ISSUE TITLE
Create a common README format

### ISSUE THREAD

**Issue by Elchi3** [mdn/mdn#1]
It would be good to come up with a standard README format for all of MDN's repositories. Tasks that I can think of:

- [ ] Collect format ideas
- [ ] Agree on what is mandatory to mention in a README file.
- [ ] Put a template into this repository.
- [ ] Roll out standardized README files to all of MDN's repos.

Inspiration:
- https://gist.github.com/PurpleBooth/109311bb0361f32d87a2
- https://github.com/kentcdodds/all-contributors
- https://github.com/mdn/webextensions-examples

**Comment by wbamberg** [comment]
For webextensions-examples, I used @ddbeck's checklist: https://github.com/ddbeck/readme-checklist. It's great.
