### ISSUE TITLE
Acknowledging Mozilla Commit Access Requirements

### ISSUE THREAD

**Issue by foolip** [mdn/mdn#101]
I have read, and agree to abide by, the [Mozilla Commit Access Requirements](https://www.mozilla.org/en-US/about/governance/policies/commit/requirements/).

This is per https://github.com/mdn/browser-compat-data/blob/master/GOVERNANCE.md#peers, where my intention is to become an invited peer for BCD.

**Comment by peterbe** [comment]
@ddbeck something you can address?

**Comment by foolip** [comment]
Indeed, it was @ddbeck who asked me to file this issue :)

**Comment by ddbeck** [comment]
Yep, this was my responsibility. Thank you, @foolip! I've opened https://github.com/mdn/browser-compat-data/pull/6560, which means this can be closed.

And it turns out that I don't have those privileges. Would you mind closing this issue, @peterbe?

**Comment by foolip** [comment]
I can close the issue since I created it, doing so now.
