### ISSUE TITLE
Text Search only in English

### ISSUE THREAD

**Issue by NagayamaToshiaki** [mdn/mdn#103]
I'm Japanese, so I use MDN of Japanese locale. When I search something, the results are always in English. Thus, I need a hustle reading them and need to find which is what I wanted to search for. Also, I can't search Japanese, because the search is handled by English.
Why Can't I search the content of Japanese MDN? I believe many non-English-natives are struggling with this issue.

**Comment by chrisdavidmills** [comment]
Hi @NagayamaToshiaki . Thanks for contacting us about this. I appreciate this must be frustrating for you, and other non-English-natives. To be honest, the English version of the search is not very effective either. The trouble is that most people use search engines to search for MDN content, and we always have higher priority engineering problems to focus on. So as a result the search has not been improved for quite a long time.

I'll pass your feedback on, but I'm going to close this for now. It is a known problem already, and we already have it in our backlog.
