### ISSUE TITLE
Suggestion on site navigation

### ISSUE THREAD

**Issue by mzoz** [mdn/mdn#104]
Dear MDN team, would you ever consider the feasibility to combine different portals like learn, tutorials, guide .etc into a single one? For example if I want to learn JavaScript systematically but will end up being confused with several root pages:
https://developer.mozilla.org/en-US/docs/Web/JavaScript
https://developer.mozilla.org/en-US/docs/Learn/JavaScript
https://developer.mozilla.org/en-US/docs/Web/Tutorials

the linked tutorials are overlapping quite a lot, just like trying to read a book with several tables of contents. As a contrary w3schools has a fairly straightforward directory:
https://www.w3schools.com/js/default.asp

Thanks!

**Comment by chrisdavidmills** [comment]
Issue moved to [mdn/sprints #3787](https://github.com/mdn/sprints/issues/3787) via [**ZenHub**](https://www.zenhub.com/)
