### ISSUE TITLE
[Feature proposal] references in snippets

### ISSUE THREAD

**Issue by mattiapontonio** [mdn/mdn#105]
Hello,

Just a little suggestion that can be an Epic.

Provide automatic references from the CSS rendered snippets to the property / statment MDN page.
Maybe a tooltip or something not invasive.
GitHub made something similar with the web version with the class definitions, it provides internal links in the repository.

**Comment by chrisdavidmills** [comment]
Issue moved to [mdn/kuma #7560](https://github.com/mdn/kuma/issues/7560) via [**ZenHub**](https://www.zenhub.com/)
