### ISSUE TITLE
Reflect deleteProperty() wiki seems missing 

### ISSUE THREAD

**Issue by 2shraaf** [mdn/mdn#107]
When I go to https://wiki.developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Reflect/deleteProperty, it view Reflect.defineProperty() wiki not deleteProperty

**Comment by chrisdavidmills** [comment]
Issue moved to [mdn/sprints #3826](https://github.com/mdn/sprints/issues/3826) via [**ZenHub**](https://www.zenhub.com/)
