### ISSUE TITLE
String.prototype.replaceAll doesn't actually exist?

### ISSUE THREAD

**Issue by bduffany** [mdn/mdn#108]
https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/String/replaceAll

`string.replaceAll` is not a real method, so this article should probably be deleted or updated for browser compatibility (`replaceAll` definitely does not work in Chrome)

This probably confuses a _ton_ of developers; no idea how this hasn't been caught by now.

**Comment by bduffany** [comment]
Nevermind, realized my version of Chrome is out of date.

**Comment by peterbe** [comment]
Kinda makes you wish the interactive example code should have a test for this integrated. E.g.

```javascript
if (!String.prototype.replaceAll) {
  console.warn("Your browser does not support replaceAll()");
}
```

But I'm not entirely sure if that's fair because then we should have lines like that in ALL interactive examples that depend on APIs that are recent additions.
