### ISSUE TITLE
Missing statment in side bar 

### ISSUE THREAD

**Issue by Avivhdr** [mdn/mdn#110]
On the [Statements and declaration](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Statements) page, all the statements appear both in the body of the page and in the side menu.
The deprecated `for each...in` appears in the body of the page but NOT in the side menu.

When trying to edit the page I could only edit the body and not the side menu.

![image](https://user-images.githubusercontent.com/23265867/102063065-d719b480-3df5-11eb-9120-0ae1d6f01d8b.png)

**Comment by chrisdavidmills** [comment]
This is because `for each ... in` has been moved to the MDN archive section, so it will no longer appear in the list of JS statements. I don't think this is a huge problem, as it is deprecated. I've added some text to the page to say it is deprecated.

**Comment by Avivhdr** [comment]
Great.
For consistency, you can add it to the `with` statement (on the side menu it has the thumb down)
