### ISSUE TITLE
The Examples of WebGLRenderingContext.createRenderbuffer() got wrong

### ISSUE THREAD

**Issue by jiangheng90** [mdn/mdn#113]
In Your WebGL API Doc [WebGLRenderingContext.createRenderbuffer()](https://developer.mozilla.org/en-US/docs/Web/API/WebGLRenderingContext/createRenderbuffer)

your example is 
```javascript
var canvas = document.getElementById('canvas');
var gl = canvas.getContext('webgl');
var renderBuffer = gl.createRenderBuffer();
```
In the last line got error, it should be
```javascript
var renderBuffer = gl.createRenderbuffer();
```

**Comment by chrisdavidmills** [comment]
Fixed by https://github.com/mdn/content/commit/d26b9994ad102c2d79a76ace5ad6c0f53b0f3e78

Thanks for reporting this @jiangheng90 !
