### ISSUE TITLE
How to change default Screenshot name in Firefox?

### ISSUE THREAD

**Issue by TechAndNews** [mdn/mdn#13]
Also, as of Firefox 52+, Full-Page Screenshots no longer work using F12 DevTools - Screenshot Button. Only captures what is viewable in window.

![ff-devtools](https://cloud.githubusercontent.com/assets/7966743/24421716/1fd14b16-13c5-11e7-8d24-6289999fbde6.png)

**Comment by Elchi3** [comment]
Hi, questions regarding DevTools can be asked in the Mozilla community discourse: https://discourse.mozilla-community.org/c/devtools
