### ISSUE TITLE
Re-write 'matching browser features' once moved

### ISSUE THREAD

**Issue by Rumyra** [mdn/mdn#132]
Re-write/edit 'matching browser features' article once it has been moved to bcd repo

**Comment by Rumyra** [comment]
@queengooborg this has been moved now right?

**Comment by queengooborg** [comment]
It has, yes!

**Comment by Rumyra** [comment]
In which case I'll assign to you and whenever you get around to checking the docs you've moved you can tackle it :D

**Comment by queengooborg** [comment]
Looking at this again, I feel that the document is actually good enough.  Since it was moved over, sections for derivative browsers were added, old links were scrapped, and sections were reorganized to make better sense.  I'm feeling like we can call this "good", WDYT?

**Comment by Rumyra** [comment]
Sounds great @queengooborg :D Thank you for taking this on!
