### ISSUE TITLE
Move & update changelog

### ISSUE THREAD

**Issue by Rumyra** [mdn/mdn#133]
Move changelog from mdn/contribute/changelog to mdn/changelog

Update with the changes we made with the Contributor docs project

**Comment by bsmth** [comment]
![Image](https://user-images.githubusercontent.com/43580235/204557140-c3f005b4-afca-4f74-a7e1-57925bfb3376.png)

**Comment by bsmth** [comment]
Open PR for these changes here:

- [ ] https://github.com/mdn/content/pull/22659
