### ISSUE TITLE
Remove update css json

### ISSUE THREAD

**Issue by Rumyra** [mdn/mdn#134]
Take any relevant information from mdn/howto/update_the_css_json_db and add to the mdn/data repository

Remove article and redirect to the mdn/data repository

**Comment by dipikabh** [comment]
Step 2 in this article https://contributor-docs.content.dev.mdn.mozit.cloud/en-US/docs/MDN/Writing_guidelines/Howto/Document_a_CSS_property refers to mdn/howto/update_the_css_json_db. This also will need to be updated appropriately.

**Comment by bsmth** [comment]
Open PRs for this:

- [ ] https://github.com/mdn/content/pull/22657
- [ ] https://github.com/mdn/data/pull/628
