### ISSUE TITLE
Redirect tools/kumascript

### ISSUE THREAD

**Issue by Rumyra** [mdn/mdn#139]
Kumascript documentation should be held on the yari repository

Information in these pages should be captured

- [ ] mdn/tools/kumascript
- [ ] mdn/tools/kumascript/troubleshooting

Pages should be removed and redirected to relevant place on yari

Articles mentioning kumascript should be updated

**Comment by bsmth** [comment]
Two PRs are open for these changes:

- [ ] https://github.com/mdn/content/pull/22638
- [ ] https://github.com/mdn/yari/pull/7713
