### ISSUE TITLE
Remove unsupported_get_api

### ISSUE THREAD

**Issue by Rumyra** [mdn/mdn#141]
Remove mdn/tools/unsupported_get_api

Again there is no good redirect for this, so should go to mdn/index.md

**Comment by sideshowbarker** [comment]
@Rumyra With https://github.com/mdn/content/pull/22147 merged, I guess this issue can be closed? (I don’t have perms here to close it myself)

**Comment by Rumyra** [comment]
Yes - thank you @sideshowbarker 👍
