### ISSUE TITLE
Remove yari article

### ISSUE THREAD

**Issue by Rumyra** [mdn/mdn#142]
Yari documentation should be held on the repository

Capture relevant info in mdn/yari

Remove and redirect to the repository

**Comment by MrBrain295** [comment]
@Rumyra I think this should be closed.

**Comment by Rumyra** [comment]
Thanks @MrBrain295 👍

**Comment by Graywolf9** [comment]
Hi! I see this is already closed but I have a doubt about l10n yari page, we should simply send to every one to the en-US info in the yari repo?

**Comment by Rumyra** [comment]
Hey @Graywolf9 - yes you bring up a very good point.

One of the reasons for this is that having repo specific info on MDN itself doesn't make a lot of sense - we have 50+ repos so we wanted to keep the information _next_ to the repo itself (if that makes sense)

I guess the question is: how much of a blocker is it for folks to have repo info in EN only.

Also we have a repo overview page https://developer.mozilla.org/en-US/docs/MDN/Community/Contributing/Our_repositories - could this be expanded a little to help?

**Comment by Graywolf9** [comment]
Thank you so much! @Rumyra that's perfect, last doubt, isn't better redirect to `https://developer.mozilla.org/en-US/docs/MDN/Community/Contributing/Our_repositories` instead of `https://github.com/mdn/yari/tree/main/docs/what-yari-does.md`

here's the actual redirect from one of the entries
```
/en-US/docs/MDN/Kuma https://github.com/mdn/yari/tree/main/docs/what-yari-does.md
```

**Comment by bsmth** [comment]
> ...redirect to `https://developer.mozilla.org/en-US/docs/MDN/Community/Contributing/Our_repositories` instead of `https://github.com/mdn/yari/tree/main/docs/what-yari-does.md`

👍🏻 sounds like a good idea to me, also

**Comment by Graywolf9** [comment]
Thank you so much! @Rumyra and @bsmth I'll make the changes
