### ISSUE TITLE
[Repo] move sw-test into dom-examples

### ISSUE THREAD

**Issue by Rumyra** [mdn/mdn#146]
https://github.com/mdn/sw-test
- [x] triage prs - 0
- [x] triage issues - 9
- [x] add contribution doc
- [x] add any notes about repo to readme
- [ ] change master to main
- [x] move if necessary - create new folder (suggest 'service-workers' folder that this is a sub folder of)
- [ ] update urls in content
- [x] archive repo if necessary
- [x] add to motherboard project

**Comment by schalkneethling** [comment]
This one is complete
