### ISSUE TITLE
[repo triage] Add history

### ISSUE THREAD

**Issue by Rumyra** [mdn/mdn#155]
- [ ] web components
- [x] simple web worker
- [x] simple shared worker
- [x] fibonacci worker
- [x] webgl examples
- [x] violent theramin
- [x] web speech api
- [x] web dictaphone
- [x] indexbd examples
- [x] canvas raycaster

**Comment by schalkneethling** [comment]
@Rumyra I think the remaining `web components` might be a typo?

**Comment by Rumyra** [comment]
Yup :)
