### ISSUE TITLE
[Repo] beginner-html-site-styled 

### ISSUE THREAD

**Issue by schalkneethling** [mdn/mdn#159]
Should we think about moving these into the larger learn repository?
https://github.com/mdn/beginner-html-site-styled

- [ ] triage prs
- [ ] triage issues
- [ ] add contribution doc
- [ ] add any notes about repo to readme
- [ ] change master to main
- [ ] move if necessary - create new folder
- [ ] update urls in content
- [ ] archive repo if necessary
- [ ] add to motherboard project

**Comment by Rumyra** [comment]
This 'needs-descision' fyi

**Comment by Rumyra** [comment]
I think we keep this repo as is - it'll be easier for beginners - at some point we can revisit when we take a look at the Learn area
