### ISSUE TITLE
Follow up on some repos

### ISSUE THREAD

**Issue by Rumyra** [mdn/mdn#162]
- [x] devtools examples https://github.com/mdn/devtools-examples we removed docs a while ago and does the team want this examples?
- [x] nss-docs https://github.com/mdn/nss-docs I think archive 
- [x] Rename imsc to imsc-examples

**Comment by schalkneethling** [comment]
Spoke to some folks on the #security channel on Slack, and Benjamin Beurdouche gave the green light to archive the `nss-docs` repo.

**Comment by schalkneethling** [comment]
The devtools folks are in GHE, and so they will have to open an issue for someone from IT to transfer the repo. I will update the issue once it has been transferred.

**Comment by schalkneethling** [comment]
`imsc` is renamed and PR ready for review: https://github.com/mdn/content/pull/20871

**Comment by schalkneethling** [comment]
Here is the Bugzilla ticket to transfer devtools-examples to the devtools org. https://bugzilla.mozilla.org/show_bug.cgi?id=1791362

**Comment by schalkneethling** [comment]
Devtools examples have been transferred - https://github.com/firefox-devtools/devtools-examples 🙌
