### ISSUE TITLE
[Repo] Move audio-channels-demo to web-audio-examples

### ISSUE THREAD

**Issue by Rumyra** [mdn/mdn#163]
- [ ] triage prs
- [ ] triage issues
- [ ] add contribution doc
- [ ] add any notes about repo to readme
- [ ] change master to main
- [ ] move if necessary - create new folder - keep history https://hacks.mozilla.org/2022/08/merging-two-github-repositories-without-losing-commit-history/
- [ ] update urls in content
- [ ] archive repo if necessary
- [ ] add to motherboard project

**Comment by schalkneethling** [comment]
@Rumyra, I notice that this one is archived, but I am not sure that we moved it to web audio examples. I see in the README it mentions that it is (was?) Firefox OS only so, perhaps just archiving was the intent?
