### ISSUE TITLE
[Repo] move voice-change-o-matic to webaudio-examples

### ISSUE THREAD

**Issue by Rumyra** [mdn/mdn#164]
NB there are two voice-change-o-matics, retire one of them and update MDN copy to reflect

- [x] triage prs
- [x] triage issues
- [x] add contribution doc
- [x] add any notes about repo to readme
- [x] change master to main
- [x] move if necessary - create new folder - keep history https://hacks.mozilla.org/2022/08/merging-two-github-repositories-without-losing-commit-history/
- [x] update urls in content
- [x] archive repo if necessary
- [x] add to motherboard project

**Comment by bsmth** [comment]
* [x] https://github.com/mdn/voice-change-o-matic
* [x] https://github.com/mdn/voice-change-o-matic-float-data
* [x] https://github.com/mdn/webaudio-examples/pull/92

**Comment by Rumyra** [comment]
Awesome - thanks @bsmth
