### ISSUE TITLE
[Repo] Move fetch-examples to dom-examples

### ISSUE THREAD

**Issue by Rumyra** [mdn/mdn#165]
https://github.com/mdn/fetch-examples
- [x] triage prs - 1
- [x] triage issues - 3
- [ ] add contribution doc
- [x] add any notes about repo to readme
- [x] change master to main
- [x] move if necessary - create new folder
- [x] update urls in content
- [x] archive repo if necessary
- [ ] add to motherboard project

**Comment by schalkneethling** [comment]
This one is complete.
