### ISSUE TITLE
Create a Code of Conduct

### ISSUE THREAD

**Issue by Elchi3** [mdn/mdn#2]
This repository should contain the Code of Conduct for this organization, so that we can link to it from the individual repositories (for example from a standardized README file, see #1).

**Comment by wbamberg** [comment]
Why not use Mozilla's CoC, and just link to it, like https://github.com/mdn/webextensions-examples/blob/master/CODE_OF_CONDUCT.md ?

**Comment by Elchi3** [comment]
Great idea! I like it.

**Comment by teoli2003** [comment]
I've create the PR for it (after fixing a double typo in the original one that lead to links not being real links) See https://github.com/mdn/mdn/pull/10

**Comment by Elchi3** [comment]
Thanks @teoli2003
