### ISSUE TITLE
Link on developer.mozilla.org refers to not-existing mdn.github.io

### ISSUE THREAD

**Issue by HarmlessEvil** [mdn/mdn#20]
Link on [this](https://developer.mozilla.org/ru/docs/Web/JavaScript/Reference/Global_Objects/Promise) page (at the bottom of an article refers to non-existing site: http://mdn.github.io/promises-test/)

**Comment by jwhitlock** [comment]
The links were correct on the English version, and I've updated them on the Russian translation:

* https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Promise
* https://developer.mozilla.org/ru/docs/Web/JavaScript/Reference/Global_Objects/Promise
* https://github.com/mdn/js-examples/tree/master/promises-test
* https://mdn.github.io/js-examples/promises-test/

I'm not a Russian speaker, so you may want to review my changes.

The "official" place for content bugs is Bugzilla, against the Developer Documentation component:

https://bugzilla.mozilla.org/enter_bug.cgi?product=Developer%20Documentation
