### ISSUE TITLE
[Repo] Learning-area-pt-br

### ISSUE THREAD

**Issue by Rumyra** [mdn/mdn#216]
Check to see if it's ok archiving

- [x] triage prs
- [x] triage issues
- [ ] add contribution doc
- [x] add any notes about repo to readme
- [x] change master to main
- [ ] move if necessary - create new folder - keep history https://hacks.mozilla.org/2022/08/merging-two-github-repositories-without-losing-commit-history/
- [ ] update urls in content
- [x] archive repo if necessary
- [ ] add to motherboard project

**Comment by schalkneethling** [comment]
I asked the team two weeks ago and got no feedback, I believe that is a signal that we can archive.
