### ISSUE TITLE
[Repo] Advanced-js-fundamentals-ck

### ISSUE THREAD

**Issue by Rumyra** [mdn/mdn#219]
Check to make sure it's not needed

- [x] triage prs
- [x] triage issues
- [ ] add contribution doc
- [ ] add any notes about repo to readme
- [x] change master to main
- [ ] move if necessary - create new folder - keep history https://hacks.mozilla.org/2022/08/merging-two-github-repositories-without-losing-commit-history/
- [ ] update urls in content
- [x] archive repo if necessary
- [ ] add to motherboard project

**Comment by schalkneethling** [comment]
The last update to this repository was seven years ago, and the last issue was filed in 2016. We also do not have a ck team so, I am going to go ahead and archive this one.
