### ISSUE TITLE
[Repo] Browser-api-demo

### ISSUE THREAD

**Issue by Rumyra** [mdn/mdn#220]
The page has been removed from MDN so this should be good to archive

- [x] triage prs
- [ ] triage issues
- [ ] add contribution doc
- [ ] add any notes about repo to readme
- [x] change master to main
- [ ] move if necessary - create new folder - keep history https://hacks.mozilla.org/2022/08/merging-two-github-repositories-without-losing-commit-history/
- [ ] update urls in content
- [x] archive repo if necessary
- [ ] add to motherboard project

**Comment by schalkneethling** [comment]
This has been archived.
