### ISSUE TITLE
[Repo] Webvr-tests

### ISSUE THREAD

**Issue by Rumyra** [mdn/mdn#221]
WebVR is deprecated so we can archive to avoid updates

- [x] triage prs
- [x] triage issues
- [ ] add contribution doc
- [x] add any notes about repo to readme
- [x] change master to main
- [ ] move if necessary - create new folder - keep history https://hacks.mozilla.org/2022/08/merging-two-github-repositories-without-losing-commit-history/
- [x] update urls in content
- [x] archive repo if necessary
- [ ] add to motherboard project

**Comment by schalkneethling** [comment]
This is now in the museum: https://github.com/mdn/museum/tree/main/webvr
