### ISSUE TITLE
List browsers/platforms to help with guidelines moving forward

### ISSUE THREAD

**Issue by Rumyra** [mdn/mdn#223]

**Comment by Rumyra** [comment]
Amazing @queengooborg - this is super helpful, thank you!

**Comment by robnyman** [comment]
Very interesting!
One small nit: It's not Chrome, it's Chromium. And Gecko. and WebKit, not Safari.

**Comment by queengooborg** [comment]
I'm listing the browsers rather than the engines, so "Chrome", "Firefox" and "Safari" are accurate.  :)

**Comment by robnyman** [comment]
It's a different thing. Microsoft Edge isn't Chrome, and shouldn't belong to that top category. Chrome is a Google product. Chromium is the open source project, containing the rendering engine.

**Comment by queengooborg** [comment]
I'm not trying to imply that Chrome and Edge are the exact same in this list.  I'm merely grouping the browsers by their engine, and placing the dominant browser of that engine as the top list item!

**Comment by Rumyra** [comment]
Just to add context, this was a preliminary list just to get an idea of the landscape.

If we use it as inspiration for questions/surveys moving forward I wouldn't expect to separate the different engines anyway 👍
