### ISSUE TITLE
Nominating a co-maintainer for interactive examples

### ISSUE THREAD

**Issue by schalkneethling** [mdn/mdn#224]
### Given name or GitHub username

NiedziolkaMichal

### GitHub profile link

https://github.com/NiedziolkaMichal

### Why are you nominating this individual?

@NiedziolkaMichal has been prolific with his contributions to the `interactive-examples` repository and also demonstrates dedication and understanding of the project's needs and goals. He has also contributed some critical updates to the `bob` repo: https://github.com/mdn/bob/commits?author=NiedziolkaMichal and https://github.com/mdn/bob/pulls?q=is%3Apr+is%3Aopen+author%3ANiedziolkaMichal+sort%3Aupdated-desc

It has also been suggested by members of Open Web Docs to nominate Michal. I strongly suggest we reach out to Michal and determine whether he would be interested in this [additional responsibility](https://developer.mozilla.org/en-US/docs/MDN/Community/Users_teams#volunteer_and_partner_maintainers).

### Supporting evidence

https://github.com/mdn/interactive-examples/commits?author=NiedziolkaMichal

### Repository URL

https://github.com/mdn/interactive-examples

**Comment by NiedziolkaMichal** [comment]
That sounds great, thank you for the opportunity.

**Comment by schalkneethling** [comment]
> That sounds great, thank you for the opportunity. I agree to [Community Participation Guidelines](https://www.mozilla.org/en-US/about/governance/policies/participation/) and [Commit Access Requirements](https://www.mozilla.org/en-US/about/governance/policies/commit/requirements/). I have also created [profile](https://people.mozilla.org/p/niedziolka_michal) on [people.mozilla.org](https://people.mozilla.org/) and activated two-factor authentication on github

Excellent, thanks so much for getting started on all of that @NiedziolkaMichal 🎉

**Comment by schalkneethling** [comment]
@NiedziolkaMichal is now an NDA'd co-maintainer of the interactive examples project. 🎉
