### ISSUE TITLE
Sunset German and Polish

### ISSUE THREAD

**Issue by schalkneethling** [mdn/mdn#228]
Archive the German and Polish content of MDN Web Docs.

**Comment by adlai** [comment]
From my outsider perspective, this suggests that the native speakers of those languages have sufficiently high levels of English fluency, that translator effort was misguided... where was the rationale for the sunsetting documented?

**Comment by caugner** [comment]
@adlai You can find more information in [this announcement](https://github.com/mdn/mdn-community/discussions/147).
