### ISSUE TITLE
MDN 'what we've done' blog post

### ISSUE THREAD

**Issue by schalkneethling** [mdn/mdn#243]

**Comment by schalkneethling** [comment]
@dipikabh @bsmth Are we good here? Is there anything else needed from us concerning the blog post?

**Comment by dipikabh** [comment]
There does not seem to be anything outstanding as of now. There might be a final readthrough required though.

**Comment by schalkneethling** [comment]
> There does not seem to be anything outstanding as of now. There might be a final readthrough required though.

@HerminaC thoughts?

**Comment by Rumyra** [comment]
Yes we haven't come back to this since it's been on pause - unsure of the status at this time, but will update issue to reflect

**Comment by schalkneethling** [comment]
> Why is this considered part of `chores`, i.e. "keeping the lights on"?

The description of "chore" is not quite accurate :)

**Comment by schalkneethling** [comment]
> Yes we haven't come back to this since it's been on pause - unsure of the status at this time, but will update issue to reflect

I believe this is ready so, we should touch base with Melissa and have it published.

**Comment by Rumyra** [comment]
This is referring to the 'What we've done' post not the community docs post fyi (which @schalkneethling you were doing today) 👍

**Comment by adlai** [comment]
At the risk of arguing for free...

> > Why is this considered part of `chores`, i.e. "keeping the lights on"?
> The description of "chore" is not quite accurate :)

... it actually is. Your employer is not a fully-owned subsigiary of the Alphabet Corporation.

**Comment by schalkneethling** [comment]
@adlai, please note that we have dozens of people watching this repository. For every comment posted, these people may receive a notification.

Please be respectful of other people’s time and attention, and avoid taking actions that might cause excessive notifications. Issues should describe a problem or propose an actionable solution. Please use the [MDN Web Docs feedback repository](https://github.com/mdn/feedback/discussions) if a discussion is needed.

Also, please remember that the [Mozilla Community Participation Guidelines](https://www.mozilla.org/en-US/about/governance/policies/participation/) govern all participation in these open spaces. We enforce these to maintain a healthy and inviting community experience for everyone.

To give everyone a moment to reconsider the best way forward, we will lock this issue for 24 hours.

**Comment by bsmth** [comment]
I believe this is published at https://hacks.mozilla.org/2022/10/revamp-of-mdn-web-docs-contribution-docs/, closing now.

**Comment by Rumyra** [comment]
Still again

> This is referring to the 'What we've done' post not the community docs post fyi (which @schalkneethling you were doing today) 👍

I'm going to leave it closed however because we haven't revisited the original post and until we do it may as well stay closed as it's causing so much activity :)
