### ISSUE TITLE
Page redirect for locale doen't work as expected

### ISSUE THREAD

**Issue by TakayoshiKochi** [mdn/mdn#25]
Due to my locale preference, Google search prefers Japanese page to other locales.

For example, for my query "HTMLElement", it returns
https://developer.mozilla.org/ja/docs/Web/API/HTMLElement
as the first result.

Then I switch the language on top-right link to "en-US", then this popup asks me if I want to view pages in that locale.
![fvfuqydfshm](https://user-images.githubusercontent.com/4220972/37138873-1d33c0ac-22ef-11e8-98b8-9d80e81eca57.png)

But after answering "Yes" to this, if I do the search again, and follow the link for "ja" locale - I expected MDN to redirect to en-US if available, but it doesn't work.

Is this working as expected?
if so, what the real expectation for the answer for the popup?

**Comment by GloverDonovan** [comment]
Hi @TakayoshiKochi,

Issues regarding MDN are reported through Bugzilla (mozilla/kuma#2941).

This seems like a duplicate of https://bugzilla.mozilla.org/show_bug.cgi?id=926963.

**Comment by jwhitlock** [comment]
@GloverDonovan is right, Bugzilla, not this repository, is where to report developer.mozilla.org bugs.  https://bugzilla.mozilla.org/show_bug.cgi?id=1440602 has some more explanation of the issue.

**Comment by TakayoshiKochi** [comment]
Thanks for the pointers, @GloverDonovan and @jwhitlock !
I'll follow those bugs.
