### ISSUE TITLE
Add `scrollend` event

### ISSUE THREAD

**Issue by argyleink** [mdn/mdn#252]
### Proposed

10/31/2022

### Proposed by

argyleink

### Informed

https://github.com/whatwg/html/pull/8433

### Proposal

The [`scrollend`](https://github.com/whatwg/html/pull/8433) event has two implementors and is looking to link to the MDN issue/page. 

spec https://drafts.csswg.org/cssom-view/#scrolling

behind a flag in Canary and [Firefox]([bug 1797013](https://bugzilla.mozilla.org/show_bug.cgi?id=1797013))

### Context

Folks will be looking for a good api page once they begin working with it, or to even discover it's available. 

### Consequences

work to be done on the page for MDN

### Alternatives

none

**Comment by argyleink** [comment]
https://chromestatus.com/feature/5186382643855360

**Comment by Rumyra** [comment]
Thanks so much @argyleink - sorry it took me some time to get back to this.

I've opened a task issue which @bsmth will pick up and we'll get the docs up :) https://github.com/mdn/content/issues/22814

The work can be tracked in the linked issue, so I'll close this one - thanks again for adding! In other news I've updated our suggestion form, so it should be a little less friction to make suggestions like this for us in the future 👍
