### ISSUE TITLE
Add renovate to bob and interactive examples repos

### ISSUE THREAD

**Issue by schalkneethling** [mdn/mdn#28]
I would love to add [greenkeeper](https://github.com/apps/greenkeeper) to the /bob and /interactive-examples repos. This will automate away the responsibility for keeping dependencies up to date. This will also ensure we do not have dependencies with security vulnerabilities.

A situation we are currently in. Thanks!

**Comment by jwhitlock** [comment]
I've heard some others (@peterbe, @openjck) recommend https://renovatebot.com/ over GreenKeeper. The main complaint is that greenkeeper just updates ``package.json``, while renovate runs ``yarn upgrade``, updating the ``yarn.lock`` file. Is that something we're interested in?

**Comment by schalkneethling** [comment]
Yup, Renovate would actual be preferred.

**Comment by openjck** [comment]
I definitely recommend Renovate. Greenkeeper does ostensibly support lockfiles, but not without headache. I've never actually been able to make it work.

**Comment by jwhitlock** [comment]
OK, looking over Renovate's terms of service, install instructions, etc.

**Comment by jwhitlock** [comment]
The terms look good, and no charge for open source projects. I've enabled Renovate for:

* https://github.com/mdn/bob - https://github.com/mdn/bob/pull/26
* https://github.com/mdn/interactive-examples - https://github.com/mdn/interactive-examples/pull/850

Also, greenkeeper is already configured for https://github.com/mdn/doc-linter-webextension. @MatonAnthony, if you want to switch to Renovate, let me know. Or tell us that we're all wrong about greenkeeper.

**Comment by schalkneethling** [comment]
Thanks @jwhitlock
