### ISSUE TITLE
[PROJECT] Retitle Web/API pages

### ISSUE THREAD

**Issue by wbamberg** [mdn/mdn#284]
### Proposal

For a long time the titles we use for Web/API pages have been a problem: apart from the fact that they are wrong for non-static members, they don't allow us to distinguish static and instance members.

There's a very long discussion about what to do about this here: https://github.com/orgs/mdn/discussions/248 which eventually resulted in a plan for what to do about it here: https://github.com/orgs/mdn/discussions/248#discussioncomment-4211620, that renames pages based on the proposal at https://github.com/orgs/mdn/discussions/248#discussioncomment-3797416.

Note that this _does not_ yet actually enable us to have static and instance members with the same name, as requested in https://github.com/openwebdocs/project/issues/104 - for that we would also need a convention for different URLs for static and instance members. But this project is a necessary component of that work.

https://github.com/mdn/mdn/issues/284#tasklist-block-9dfc6abf-98b0-4987-993a-7dc208d5ca11

### Are you willing to support this work?

Yes.

### Depends on

No.

**Comment by wbamberg** [comment]
Filed https://github.com/mdn/yari/pull/7825 for the `short-title` bit of this.

**Comment by Rumyra** [comment]
Thanks @wbamberg ! I'm going to edit the description a little and create a 'tasklist' with the afore mentioned issue :)

**Comment by teoli2003** [comment]
Congrats to @wbamberg for the fantastic work done here!

This is done.
