### ISSUE TITLE
learning-area

### ISSUE THREAD

**Issue by dipikabh** [mdn/mdn#302]
Following the guidelines defined in https://github.com/mdn/mdn/issues/168

#### General

- [x] A default or custom social share image (added)
- [x] "Preserve this repository" (already selected)
- [ ] Pull request: "Allow squash merging" -> Default to PR title for squash merge commits (selected "Default to pull request title")
- [x] "Always suggest updating pull request branches" (turned on)
- [x] "Automatically delete head branches"  (turned on)
- [x] Disable wiki & projects - as per repo save wiki if necessary ("Wikis", "Discussions", and "Projects" are already disabled)

#### Branches
- [x] Ensure default branch is `main` (already `main`)
Branch protection for the main branch (added):
- [x] "Require a pull request before merging" (turned this on)
- [x] "Require status checks to pass before merging" (turned this on)
- [x] "Require branches to be up to date before merging" (turned this on)
- [ ] "Require signed commits" if appropriate

#### Actions
- [ ] Welcome action
- [ ] Enable CodeQL
- [ ] Idle workflow
- [ ] Prettier if appropriate
- [ ] Editor config if appropriate
- [ ] Add template docs

#### Environments, Releases, Packages
- [ ] Disable environments, releases & packages if appropriate (no Release or Packages)

### Issue/PR/label/discussion triage

- [ ] Common set of labels
- [ ] Edit existing labels as per repository
- [ ] Issue templates (forms) https://github.com/mdn/project-template/tree/main/.github
- [ ] PR template https://github.com/mdn/project-template/blob/main/.github/PULL_REQUEST_TEMPLATE
- [ ] Triage issues, pull requests & discussion (a rough triage rather than a detailed one - try and get things in right place)
- [ ] Move all 'suggestions' to the mdn/mdn repo and add label needs triage
- [ ] Remove all discussions and shut down feature (apart from mdn-community & translated-content)
- [ ] Assign tier 2 repos

**Comment by Rumyra** [comment]
Closing this as we'll revisit (and re plan) some of the work later in the year
