### ISSUE TITLE
translated-content

### ISSUE THREAD

**Issue by dipikabh** [mdn/mdn#304]
Following the guidelines defined in https://github.com/mdn/mdn/issues/168

#### General

- [x] A default or custom social share image (added)
- [x] "Preserve this repository" (already selected)
- [ ] Pull request: "Allow squash merging" -> "Default to pull request title and commit details" (already enabled)
- [x] "Always suggest updating pull request branches" (already enabled)
- [x] "Automatically delete head branches"  (already enabled)
- [ ] Disable wiki & projects - as per repo save wiki if necessary ("Wikis" is turned off, "Discussions", "Projects",  and "Projects (classic) are selected. Let this be as is?)

#### Branches
- [x] Ensure default branch is `main` (already `main`)
Branch protection for the main branch (exists):
- [ ] "Require a pull request before merging" (Let this be as is? it is off)
- [x] "Require status checks to pass before merging" (already enabled)
- [ ] "Require branches to be up to date before merging" (Let this be as is? it is off)
- [ ] "Require signed commits" if appropriate

#### Actions
- [ ] Welcome action
- [ ] Enable CodeQL
- [ ] Idle workflow
- [ ] Prettier if appropriate
- [ ] Editor config if appropriate
- [ ] Add template docs

#### Environments, Releases, Packages
- [x] Disable environments, releases & packages if appropriate (no Environments, Releases, or Packages)

### Issue/PR/label/discussion triage

- [ ] Common set of labels
- [ ] Edit existing labels as per repository
- [ ] Issue templates (forms) https://github.com/mdn/project-template/tree/main/.github
- [ ] PR template https://github.com/mdn/project-template/blob/main/.github/PULL_REQUEST_TEMPLATE
- [ ] Triage issues, pull requests & discussion (a rough triage rather than a detailed one - try and get things in right place)
- [ ] Move all 'suggestions' to the mdn/mdn repo and add label needs triage
- [ ] Remove all discussions and shut down feature (apart from mdn-community & translated-content)
- [ ] Assign tier 2 repos

**Comment by Rumyra** [comment]
Closing this as we'll revisit (and re plan) later in the year
