### ISSUE TITLE
Wikipedia like hover animation on hyperlinks

### ISSUE THREAD

**Issue by Overproness** [mdn/mdn#319]
### Proposal

On Wikipedia, when you hover over an embedded hyperlink, it shows you the basic definition of that thing. This feature is especially useful when someone doesn't want to know everything about a particular topic and instead just wants some basic information. This will help them understand the current topic without having to open a link in a new tab. I have attached the video of the implementation on Wikipedia. 

https://user-images.githubusercontent.com/66616578/209555755-1b9a16d3-6e7b-4908-a563-4f857f6d636a.mp4

### Task list

- [ ] 
Decide on a design that best matches the aesthetics of MDN (Dark & Light Theme)
Write the necessary HTML, CSS & JavaScript Code
Testing & Optimization
(If required, release an experimental version at first to check the user's feedback. ) Release it on the whole website. 

### Are you willing to support this work?

Yes

**Comment by nschonni** [comment]
Those type of hover things are usually not accessible or mobile friendly

**Comment by Overproness** [comment]
I see. Thanks anyways
