### ISSUE TITLE
Scroll-linked animations: View progress timelines

### ISSUE THREAD

**Issue by Rumyra** [mdn/mdn#340]
### Proposal

The scroll-linked animations spec includes view progress timelines. These are not yet documented on MDN, however at the time of writing shouldn't because of browser implementation status.

Including in the roadmap to make a note of future work.

See: https://w3c.github.io/csswg-drafts/scroll-animations/

### Task list

- [ ] Review spec and outline work
- [ ] Check scroll progress timelines is up to date

### Depends on

Browser implementation

**Comment by dipikabh** [comment]
view-timeline work (https://w3c.github.io/csswg-drafts/scroll-animations/#view-timelines) is being implemented via https://bugzilla.mozilla.org/show_bug.cgi?id=1737920

**Comment by Rumyra** [comment]
Closing as work has been done as part of FF releases
