### ISSUE TITLE
scrollTimeline API

### ISSUE THREAD

**Issue by bsmth** [mdn/mdn#346]
### Proposal

It looks like we're missing docs for https://drafts.csswg.org/scroll-animations-1/#scrolltimeline

### Task list

- [ ] Assess implementations
- [ ] Check overlap with https://developer.mozilla.org/en-US/docs/Web/CSS/scroll-timeline (note BCD shows not much compat)

**Comment by bsmth** [comment]
See also: https://github.com/mdn/mdn/issues/340

**Comment by Rumyra** [comment]
ScrollTimeline interface is documented here https://developer.mozilla.org/en-US/docs/Web/API/ScrollTimeline so closing
