### ISSUE TITLE
CSS Custom Highlight API

### ISSUE THREAD

**Issue by dipikabh** [mdn/mdn#348]
### Proposal

This API needs to be documented based on implementation in browsers.

Spec: https://drafts.csswg.org/css-highlight-api-1/

```[tasklist]
### Tasks
- [x] Document the API
- [x] Update bcd
- [ ] Check through MDN content issues to see if any have been closed due to the work
```

**Comment by captainbrosset** [comment]
I started working on this yesterday. Please do assign this to me.

**Comment by Rumyra** [comment]
It's on the roadmap @captainbrosset thank you! I'm going to edit the description a little bit too - if there's any tasks to keep track of just add them to the task list (assuming you have access, lmk if you don't) 👍

**Comment by captainbrosset** [comment]
I think this item can be closed now. The new documentation was merged yesterday: https://developer.mozilla.org/en-US/docs/Web/API/CSS_Custom_Highlight_API

I haven't looked at task 3 in the list though.

**Comment by Rumyra** [comment]
I checked through the issues and looks like we're all good - thanks @captainbrosset !
