### ISSUE TITLE
make table headers sticky on comp-tables

### ISSUE THREAD

**Issue by jimmywarting** [mdn/mdn#349]
### Proposal

the comp. table on eg https://developer.mozilla.org/en-US/docs/Web/API/RTCDataChannel#browser_compatibility and some others are quite long... so when you scroll down then you don't know what browser you are looking at.

i would like it very much if the headers where position stick so it follow downwards when you scroll

**Comment by caugner** [comment]
Thank you @jimmywarting, and sorry for the long triage time.

The sticky BCD table header has been previously requested in https://github.com/mdn/yari/issues/5417, and there was a work-in-progress PR (https://github.com/mdn/yari/pull/8541), so I will go ahead and close this issue as a duplicate, and move it to yari.
