### ISSUE TITLE
Add Irene Smith to a MDN repository

### ISSUE THREAD

**Issue by jwhitlock** [mdn/mdn#35]
@jmswisher requested that @irenesmith needs to be added to one or more MDN repositories, so that she can be assigned sprint tasks. Which repositories does she need access to?

**Comment by irenesmith** [comment]
I have access to browser-compat-data already. I've forked it an submitted
several pull requests.

**Comment by jwhitlock** [comment]
Admins on https://github.com/mdn/interactive-examples are @atopal, @schalkneethling, and @jmswisher. It looks like there is a pending invite to @techwriter13, which might be an old account.

@jmswisher is the only admin on https://github.com/mdn/data, which seems wrong...

**Comment by irenesmith** [comment]
@techwriter13 is the git account I had at a different job. Any invitation
should go to @irenesmith which I have associated with my Mozilla email.

**Comment by schalkneethling** [comment]
@jwhitlock @irenesmith I have retracted the previous invite and sent a new one to the correct username for Irene on interactive examples.

**Comment by irenesmith** [comment]
And I have accepted. Thanks!

**Comment by jmswisher** [comment]
> @jmswisher is the only admin on https://github.com/mdn/data, which seems like too few...

I think that is because I am the only member of the "Project Managers" group, which has admin on that repo. Somebody more involved with the repo, such as @Elchi3 or @wbamberg should be added as admin.

**Comment by jwhitlock** [comment]
I've invited @irenesmith to the mdn/data repository. We still need an admin for that repo, but that's a different issue.
