### ISSUE TITLE
Add documentation for CSS nesting

### ISSUE THREAD

**Issue by argyleink** [mdn/mdn#359]
### Proposal

CSS [`nesting`](https://drafts.csswg.org/css-nesting/) has an [intent to ship](https://groups.google.com/a/chromium.org/g/blink-dev/c/eFCrkiLynfU/m/JLsh3zQuAAAJ) from Safari and Chromium ([Chrome status](https://chromestatus.com/feature/5800613594529792)). [The spec](https://drafts.csswg.org/css-nesting/) is in a good place for MDN to begin documenting it. 

### Task list

- [ ] Add new page for nesting
- [ ] Add examples
- [ ] Update other documentation to point to the new page

### Are you willing to support this work?

I can review for sure!

**Comment by Rumyra** [comment]
Thanks for the suggestion @argyleink !

@dipikabh can you take a look at the work needed for CSS nesting? (A review of pages et al) and add to the description. Then we can take a look at timelines etc...

**Comment by dipikabh** [comment]
@Rumyra sure, will do

**Comment by Rumyra** [comment]
This is being worked on here https://github.com/mdn/content/issues/27180

**Comment by dletorey** [comment]
I'm on this, should be done today

**Comment by dipikabh** [comment]
Closing this as duplicate of https://github.com/mdn/content/issues/27180.
