### ISSUE TITLE
[PROJECT][JS] Regular expression reference pages

### ISSUE THREAD

**Issue by bsmth** [mdn/mdn#361]
### Proposal

Add new reference pages for regular expressions in JavaScript.
Work is underway to add these pages already.

```[tasklist]
### Tasks
- [x] Add new reference pages, expanding on stubs already proposed
- [x] Improve existing resources
```

### Are you willing to support this work?

Yes

**Comment by Josh-Cena** [comment]
This project should be completed now

**Comment by bsmth** [comment]
Thanks for the reminder 🙌🏻
