### ISSUE TITLE
Prechoose the printer on opening Dialog

### ISSUE THREAD

**Issue by meldau** [mdn/mdn#368]
### Proposal

Printing is loosing importance, but not in some special business cases. With more and more online tools used for office tasks,  browsers must offer better print support.
Choosing the output way (e.g. letter or label printer) would be important to ease the work flow.

### Task list

- at least: id/number of entry in printer dropdown list
- better: a readout for a unique printer identifier, that's not changing
- also a reaturn value of "print initiated" or "canceld" would be helpful. This is missing in .print() and onafterprint

### Are you willing to support this work?

As far as I'm able to do, yes

**Comment by Rumyra** [comment]
Hi @meldau - thanks for the proposal, however this doesn't appear to be directly related to MDN Web Docs. Are you proposing functionality for the specification?

**Comment by caugner** [comment]
I agree that this does not seem to be related to MDN Web Docs, so I'm closing this issue, as there hasn't been any activity since February.
