### ISSUE TITLE
Create mdn/docs repo for documentation issues currently handled in Bugzilla

### ISSUE THREAD

**Issue by jmswisher** [mdn/mdn#37]
As part of [migrating the process for documentation issues from Bugzilla to Github](https://github.com/mdn/sprints/issues/281), there needs to be a repo in Github to house the issues. Consensus from the content team is not to use an existing repo (i.e., mdn/sprints), to avoid confusion.  

I am leaning in favor of "mdn/docs" for the name. Submitting an issue under that name implies to me "This is an issue with MDN docs." Like mdn/sprints, the new repo would for the foreseeable future contain primarily issues, and not files.

**Comment by jwhitlock** [comment]
I think ``mdn/docs`` would be a good name for the GitHub-source documents in the future. But it's not clear when that project will happen. We can use ``mdn/docs`` now and rename it later, if needed.

**Comment by jmswisher** [comment]
Using mdn/sprints for now.
