### ISSUE TITLE
Create an example of getting select text to a variable

### ISSUE THREAD

**Issue by Hellboy00000** [mdn/mdn#374]
### Proposal

 I am trying for more than 3 weeks to get the selected text in Firefox. This is giving me anxiety.

I ask here but nobody answer.
https://stackoverflow.com/questions/75453918/firefox-extension-get-text-in-context-menu-javascript

Please create and example. There are many people asking this question.

Edit
I wanted to write this here
https://github.com/mdn/webextensions-examples/issues/516
but when i selected new request, the page send me here. I don't know what is the correct place so i made the request there.

**Comment by Rob--W** [comment]
This can be closed. As noted at https://github.com/mdn/webextensions-examples/issues/516#issuecomment-1436057716 , an example already exists. It is linked from:

https://developer.mozilla.org/en-US/docs/Mozilla/Add-ons/WebExtensions/API/menus/onClicked#example_extensions

**Comment by Hellboy00000** [comment]
Thanks. You have some example for "on mouse down"?
