### ISSUE TITLE
Document the <search> element

### ISSUE THREAD

**Issue by domenic** [mdn/mdn#385]
### Proposal

https://html.spec.whatwg.org/multipage/grouping-content.html#the-search-element

https://github.com/whatwg/html/pull/7320

### Additional information

https://github.com/whatwg/html/pull/7320 contains links to various relevant browser bugs. This isn't implemented anywhere yet but probably will be soon since it's simple.

### Are you willing to support this work?

I can help review

**Comment by harrisi** [comment]
There is an issue open in [mdn/content](https://github.com/mdn/content/issues/26006) for this, with context about this not being added to documentation before an implementation exists.

**Comment by Rumyra** [comment]
THanks @domenic - this has been done 👍 https://github.com/mdn/content/issues/26006
