### ISSUE TITLE
AbortSignal.any() API

### ISSUE THREAD

**Issue by shaseley** [mdn/mdn#396]
### Proposal

Add documentation and examples for `AbortSignal.any()` (a new `AbortSignal` API).

### Additional information

 - Explainer: https://github.com/shaseley/abort-signal-any
 - Spec PR: https://github.com/whatwg/dom/pull/1152

### Are you willing to support this work?

Happy to help with questions/reviews

**Comment by dipikabh** [comment]
Hello @shaseley, the documentation for [AbortSignal.any()](https://developer.mozilla.org/en-US/docs/Web/API/AbortSignal/any_static) is now available on MDN, as addressed in mdn/content#27424. Therefore, I'll be closing this issue.
