### ISSUE TITLE
Handle default internationalization

### ISSUE THREAD

**Issue by harrisi** [mdn/mdn#400]
### Proposal

Currently, the MDN URL structure is `https://developer.mozilla.org/${language-tag}/...rest`. e.g., `https://developer.mozilla.org/en-US/docs/Web/HTML/Quirks_Mode_and_Standards_Mode`. However, if a path doesn't include the `language-tag`, it just goes to the "page not found" page. I propose injecting the language tag to the user agent's default locale if possible.

### Task list

- [ ] Confirm this is desired behavior, as opposed to requiring links to include the language
- [ ] When routing, if the path is non-empty, verify that the base includes a language tag such as `en-US`, injecting one based on request's `Accept-Language` header, if it exists

### Additional information

Firefox currently logs a warning message in the console if the document is in quirks mode (https://searchfox.org/mozilla-central/source/parser/html/nsHtml5DocumentBuilder.cpp#109-111, with the link in question being defined [here](https://searchfox.org/mozilla-central/source/devtools/server/actors/errordocs.js#139-140)), but the link is broken as it doesn't include the language code. Changing the link to include `en-US` doesn't seem correct, as the page is available in other languages.

### Are you willing to support this work?

Yes, happy to program this myself.

**Comment by harrisi** [comment]
I've now realized this should be filed in the [yari](https://github.com/mdn/yari) repo.

**Comment by Kclynn77** [comment]
Can someone explain to me what does this mean please
