### ISSUE TITLE
Collaborator access request for mdn/browser‑compat‑toolkit

### ISSUE THREAD

**Issue by ExE-Boss** [mdn/mdn#41]
I’ve been working on my local fork of [mdn/browser‑compat‑toolkit](https://github.com/mdn/browser-compat-toolkit) and would like to merge them into the upstream repository to get closer to resolving https://github.com/mdn/browser-compat-data/issues/2354.

I have read and agree to abide by the [Code&nbsp;of&nbsp;conduct](https://github.com/mdn/mdn/blob/master/CODE_OF_CONDUCT.md) and Mozilla’s [Commit Access Requirements](https://www.mozilla.org/en-US/about/governance/policies/commit/requirements/).

I also have 2FA enabled on my GitHub account.

**Comment by jwhitlock** [comment]
@ExE-Boss, I appreciate your work on the browser-compat-data project. One of the things that makes that project successful is that @Elchi3 is spending many hours setting the direction, identifying work that is suitable for collaborators, reviewing pull requests, making frequent releases, and communicating with external users. 

There is no such staff support for browser-compat-toolkit. It represents a weekend's worth of work at the Sprint 2018 Hackathon, and didn't excite the team like the conversion work. We still need to decide if this project is worth supporting.  The next step will be a staff person adopting the project, and aligning the code with today's goals, not March 2018's.

We're not ready to add collaborators to the project, which would imply that we want to support it in the future.  Feel free to fork it and make it you own.
