### ISSUE TITLE
Q: Global history of changed pages

### ISSUE THREAD

**Issue by ghost** [mdn/mdn#42]
We can get history of a single page using `$history` appended to the entry's link - but is there a similar way to get a *global* history of all recent changed pages - say, I would like to see a list of all pages has been updated since f.ex. one week ago?

If not, is this something that is doable as it would be helpful when scraping since this enable us to just scrape pages that has actually been updated/created (since last scraping) instead of the entire site.

**Comment by jwhitlock** [comment]
The [revision dashboard](https://developer.mozilla.org/en-US/dashboards/revisions) has all the recent changes. The feeds such as [en-US/docs/feeds/atom/all](https://developer.mozilla.org/en-US/docs/feeds/atom/all) might also be useful.
