### ISSUE TITLE
Intent to document Secure Payment Confirmation (SPC)

### ISSUE THREAD

**Issue by ianbjacobs** [mdn/mdn#421]
### Proposal

Hello,

W3C recently published Secure Payment Confirmation (SPC) as a W3C Candidate Recommendation Snapshot (see the [15 June CR of SPC](https://www.w3.org/TR/2023/CR-secure-payment-confirmation-20230615/)). I would like to add documentation of this API to MDN and welcome your guidance. 

### Task list

- [x] Create an [API landing page](https://developer.mozilla.org/en-US/docs/MDN/Writing_guidelines/Page_structures/Page_types#api_landing_page) for SPC. I was thinking of drawing some content from the specification and some from the [SPC explainer](https://github.com/w3c/secure-payment-confirmation/blob/main/explainer.md). 
- [x] Register browser compatibility data. SPC does not define interfaces itself, but extends some other APIs (e.g,. Web Authentication). Would it be appropriate to document SPC as a [subfeature](https://github.com/mdn/browser-compat-data/blob/main/docs/data-guidelines/index.md#parameters-and-parameter-object-features)?

### Are you willing to support this work?

I am happy to help build the landing page. I will seek assistance from colleagues for gathering the compatibility data.

**Comment by ianbjacobs** [comment]
cc @sideshowbarker, @dontcallmedom, @stephenmcgruer

**Comment by sideshowbarker** [comment]
Should this be moved to the mdn/content repo? If so, I’d move it myself, but I unfortunately don’t have the perms (though rightly, I should).

I wanted to update the labels on this, but also unfortunately because I lack the right perms in this repo, I can’t even add comments to issues here. :(

**Comment by mountainhippo** [comment]
Happy to contribute too, but am a total MDN n00b.

**Comment by Rumyra** [comment]
Thanks so much @ianbjacobs - one question before we move forward - do you know the browser implementation status of this?

**Comment by mountainhippo** [comment]
Secure Payment Confirmation is currently shipping on Chrome on Windows and Android (and so also works in Edge on Windows).

**Comment by ianbjacobs** [comment]
Hi @Rumyra,

I look forward to helping add SPC to MDN!

SPC is shipping in Chrome/Edge on MacOS, Windows, and Android. We have a test suite as well:
 https://wpt.fyi/results/secure-payment-confirmation?label=experimental&label=master&aligned

Thank you and I'll keep an eye out for next steps.
Ian

**Comment by ianbjacobs** [comment]
@Rumyra,
Colleagues and I have drafted a landing page for SPC. Would it be possible share that and get feedback? If so, what is the preferred way to share (e.g., pull request)? 

Thank you,
Ian

**Comment by ianbjacobs** [comment]
@stephenmcgruer has created a pull request for browser compatibility data:
 https://github.com/mdn/browser-compat-data/pull/20583

**Comment by ianbjacobs** [comment]
Created a pull request https://github.com/mdn/content/pull/28705

**Comment by Rumyra** [comment]
Work completed here https://github.com/mdn/content/pull/30439 ty!
