### ISSUE TITLE
Collaborator status for user a2sheppy on kumascript repo

### ISSUE THREAD

**Issue by a2sheppy** [mdn/mdn#43]
Back when I was really, really, *really* bad at Git (instead of just dodgy like I am now), I specifically asked not to be given collaborator status for kumascript, just to avoid any incidents. This is now becoming more of a hindrance than a boon, and I would like to be given collaborator status. Not being able to do things like assign reviewers and actually formally do reviews is interfering with my work. Especially now that more of our work is done on Github than originally envisioned.

As a Mozilla employee of many years, I already have my committer agreement in place, and I agree to abide by the code of conduct and have 2-factor authentication enabled. I also promise not to draw on the walls with crayons or to track mud in all over the just-polished floors.

**Comment by jwhitlock** [comment]
Thanks @a2sheppy. Your git game has improved quite a bit in 2018.
