### ISSUE TITLE
[mdn/content] Add firstInterimResponseStart property to Performance ResourceTiming (web-api-overview)

### ISSUE THREAD

**Issue by omrilotan** [mdn/mdn#433]
### Proposal

In cases where a navigation or subresource fetch encounters an interim 1xx response, e.g. 100 continue or 103 early hints, firstInterimResponseStart would now correspond to the time of that first interim response, while responseStart would correspond to the final response, e.g. with 200 status.

### Task list

- [ ] Add property to [ResourceTiming document](files/en-us/web/api/performance_api/resource_timing/index.md)
- [ ] Describe the new property in (`web/api/performanceresourcetiming/`)

### Additional information

Introduce `PerformanceResourceTiming.firstInterimResponseStart` in Chromw 115

https://developer.chrome.com/blog/chrome-115-beta/#resource-timing-expose-interim-response-times

### Are you willing to support this work?

I can add the English documents

**Comment by Elchi3** [comment]
Fixed by https://github.com/mdn/content/pull/28569
