### ISSUE TITLE
Feature Request: Native Masonry Layout Stable Release

### ISSUE THREAD

**Issue by danielhaim1** [mdn/mdn#446]
**Description:**
I'm wondering if there are any plans for a stable release for native masonry layout.

**Context:**
It's a highly sought after feature that's been neglected for years, and currently requires heavy scripting every time it's implemented.

**Challenges Faced:**
In my experience, I've encountered several challenges due to the absence of native masonry layout support:

- **Images without defined heights:** When cards or containers have images without defined heights, I often need to wait for the image to load before distributing the items properly. This can lead to suboptimal user experiences as users see content shifting around.

- **Performance Impact:** As an alternative solution provided, some resort to using absolute positioning, which relies on `window.resize` events to reposition items. This approach significantly affects performance and responsiveness, especially on larger websites.

**Why it's Important:**
Native masonry layout support would address these challenges and enhance web design capabilities, improving both user experiences and website performance.

**My Contribution:**
I'm enthusiastic about this feature and would like to contribute to its development. I have the experience and would be happy to assist in coding, testing, or documentation efforts to help bring this feature to fruition.

**Reference:**
For more information on the current state of masonry layout, please refer to [MDN's documentation](https://developer.mozilla.org/en-US/docs/Web/CSS/CSS_grid_layout/Masonry_layout).

Thank you for considering this feature request, and I look forward to contributing to its implementation.

**Comment by dipikabh** [comment]
Hello @danielhaim1, it's great to see your enthusiasm to contribute to the development of web technologies.

At MDN, we only document the behavior that browsers implement. To effect a change in what browsers support, we suggest sharing your ideas with the [W3C developer council](https://www.w3.org/developers/get-involved/). They have a [Discourse server](https://discourse.wicg.io/) and welcome feedback that spec writers can use to consider new features or refine existing specifications. Hope this helps.
