### ISSUE TITLE
Implement  two methods related to Date Object, 1: getFullMonth() and 2: getFullDate()

### ISSUE THREAD

**Issue by sufyaniqbaldev** [mdn/mdn#454]
### Proposal

Currently, getFullYear() is working fine for Safari Browser. but to get the exact date and  month every time I have to Implement this repeated logic 
`let date1 = new Date();
       
   date1 = `${date1.getFullYear()}-${
      ((date1.getMonth() + 1).toString().length < 2)
        ? '0' + (date1.getMonth() + 1)
        : date1.getMonth() + 1
    }-${
        (date1.getDate().toString().length < 2)
        ? '0' + (date1.getDate())
        : date1.getDate()
    }`;`

### Task list

- [ ] 

### Additional information

I am a Software Engineer. working for 4 years on different technologies. especially on Ruby On Rails. 
The above Date handling is communally used  for Safari otherwise we get an invalid date issue, so it will be great if we Implement these as default functions. Thanks
### Are you willing to support this work?

yes

**Comment by zfox23** [comment]
Hi @sufyaniqbaldev :) It looks like @bsmth has answered your question. I'm going to close this issue for now. If you have anything further to add, please feel free to add a new comment. Thank you for asking your question!
