### ISSUE TITLE
setHTMLUnsafe and parseHTMLUnsafe methods

### ISSUE THREAD

**Issue by josepharhar** [mdn/mdn#459]
### Proposal

In this HTML spec PR, we added two new methods: Element/ShadowRoot.setHTMLUnsafe and Document.parseHTMLUnsafe
https://github.com/whatwg/html/pull/9538

We have plans to add additional parameters to these methods for the new sanitization API, but those aren't done yet.

### Task list

- [ ] 

### Are you willing to support this work?

Yes

### Depends on

Nothing

**Comment by Rumyra** [comment]
Thanks so much @josepharhar - do you have any browser implementation bugs so we can track when the methods are implemented - thanks

**Comment by mozfreddyb** [comment]
This is already part of the HTML spec. All browser engines have committed to implement this.

    Chromium: https://bugs.chromium.org/p/chromium/issues/detail?id=1478969
    Gecko: https://bugzilla.mozilla.org/show_bug.cgi?id=1851575
    WebKit: https://bugs.webkit.org/show_bug.cgi?id=261143

**Comment by pepelsbey** [comment]
FYI, [Implemented in Chrome Beta 124](https://developer.chrome.com/blog/chrome-124-beta#sethtmlunsafe_and_parsehtmlunsafe)

**Comment by mozfreddyb** [comment]
This also shipped in Firefox 122.

**Comment by josepharhar** [comment]
This is enabled by default in chrome 124

**Comment by dipikabh** [comment]
We'll update MDN docs via https://github.com/mdn/content/issues/32731. Marking this one as duplicate.
