### ISSUE TITLE
Give an online note to the MDN website

### ISSUE THREAD

**Issue by dadajiege** [mdn/mdn#464]
### Proposal

When I read CSS content, I always need to think and summarize. The content of CSS is really difficult to understand, so I need a note bound with CSS content to help me remember it

### Task list

- [ ] 

### Are you willing to support this work?

yes,But my skills are not very strong

**Comment by caugner** [comment]
Hi @dadajiege, 👋 

Thank you for opening this issue. It looks like you're requesting away to annotate MDN pages with personal notes, and this is indeed already possible using our Collections feature: https://developer.mozilla.org/en-US/plus/docs/features/collections#adding-notes

Could you please check if this covers your use case? 🙏

**Comment by caugner** [comment]
@dadajiege Please let us know if our Collections feature covers your use case.

Otherwise, I would go ahead and close this issue. 🙂

**Comment by caugner** [comment]
Closing this issue as stale.
