### ISSUE TITLE
Add documentation for `pagereveal` event

### ISSUE THREAD

**Issue by noamr** [mdn/mdn#467]
### Proposal

See HTML spec PR: https://github.com/whatwg/html/pull/9818
`pagereveal` is a new event that is fired when the document is about to present its next frame after activation. It's useful, for example, for getting the handle of a cross-document view transition.

### Task list

- [ ]

**Comment by zfox23** [comment]
Thank you for your proposal, @noamr! We'll wait for a browser to implement this before writing any documentation.

**Comment by skyclouds2001** [comment]
seems that have been done via https://github.com/mdn/content/pull/34118
