### ISSUE TITLE
"Project managers" group on mdn/short-descriptions

### ISSUE THREAD

**Issue by jmswisher** [mdn/mdn#47]
Please add the "Project Managers" team with Admin privileges (or at least Write) to the mdn/short-descriptions repo, to enable members of that team (i.e., me) to do [ZenHub management tasks](https://help.zenhub.com/support/solutions/articles/43000037261-github-permissions-and-access-in-zenhub).

**Comment by jwhitlock** [comment]
@ddbeck, @wbamberg - I've added Project Managers with Write access.
