### ISSUE TITLE
Proposal to create a system of shortcuts to MDN using mdn.dev

### ISSUE THREAD

**Issue by pepelsbey** [mdn/mdn#475]
### Proposal

It’s not always convenient to link to certain MDN parts or resources. For example, I can text a link to [web.dev/learn](http://web.dev/learn) to a friend in any state of mind without thinking too much. Not sure if I’d handle the [developer.mozilla.org/en-US/docs/Learn](http://developer.mozilla.org/en-US/docs/Learn). I’d have to search for it first, but even then, it’s not always clear which page I need.

I’d like to suggest using the [mdn.dev](http://mdn.dev/) domain to set up a number of useful shortcuts. I’d start with a short set of links for the core team’s needs. For example:

- mdn\.dev/css
- mdn\.dev/html
- mdn\.dev/js
- mdn\.dev/discord

It would be so much easier to remember these in a pinch compared to:

- [developer.mozilla.org/en-US/docs/Web/CSS](https://developer.mozilla.org/en-US/docs/Web/CSS)
- [developer.mozilla.org/en-US/docs/Web/HTML](https://developer.mozilla.org/en-US/docs/Web/HTML)
- [developer.mozilla.org/en-US/docs/Web/JavaScript](https://developer.mozilla.org/en-US/docs/Web/JavaScript)
- [discord.gg/Gt4Qf6q67h](https://discord.gg/Gt4Qf6q67h)

This might require setting up some infrastructure to be able to add new redirects easily. Also, it might be useful to define a process of adding new ones via issue (proposal followed by discussion) and only then via PR to a config file. I think it would be good to keep the number of redirects to a minimum.

**Comment by caugner** [comment]
@nschonni I noticed that you reacted to this proposal with a 👎 . Can you please elaborate your thoughts on this?

**Comment by Josh-Cena** [comment]
FYI, this exists: https://mdn.io/Promise, https://justlink.to/mdn/Promise. I've used them in Discord.

**Comment by caugner** [comment]
We have actually implemented this in April 2024, so I'm closing this issue as resolved: https://github.com/mdn/mdn.dev

The redirects are defined in this file: https://github.com/mdn/mdn.dev/blob/main/redirects.txt

**Comment by Josh-Cena** [comment]
@caugner FYI the repo is not public
