### ISSUE TITLE
`field-sizing` CSS property

### ISSUE THREAD

**Issue by tkent-google** [mdn/mdn#476]
### Proposal

Add a document for `field-sizing` CSS property.

https://drafts.csswg.org/css-ui/#field-sizing
https://github.com/whatwg/html/pull/9903

### Task list

- [ ]

**Comment by LeaVerou** [comment]
There is an implementation of `field-sizing` in Chrome, so the "needs implementation" label should probably be removed?

**Comment by LeaVerou** [comment]
> There is an implementation of `field-sizing` in Chrome, so the "needs implementation" label should probably be removed?

Ping @pepelsbey ?

**Comment by pepelsbey** [comment]
Added in mdn/content#32489
