### ISSUE TITLE
GitHub email change not changing MDN email for confirmation email

### ISSUE THREAD

**Issue by sollyucko** [mdn/mdn#48]
For some reason, when I try to sign in/create an account with GitHub, MDN tries to send an email to the email account I originally tried to sign up for MDN with (and _was_ connected to my GitHub account via Google). I have now changed my GitHub email to an email address that can recieve emails to and gotten rid of the old one, but MDN keeps trying to email my old account. I have tried revoking permission, for MDN to access my GitHub email, but it _still_ tries to use my non-working email.

**Comment by jwhitlock** [comment]
Account help often requires talking about email and account details, and GitHub issues are public by default. I've moved this discussion to https://bugzilla.mozilla.org/show_bug.cgi?id=1514492
