### ISSUE TITLE
Document CSS Anchor positioning

### ISSUE THREAD

**Issue by JustinWebDev** [mdn/mdn#483]
### Proposal

ref:
https://webdesign.tutsplus.com/what-is-css-anchor-positioning--cms-107415a
https://www.youtube.com/watch?v=B4Y9Ed4lLAI

### Tasks

- [ ]

### Dependencies

- [ ]

**Comment by pepelsbey** [comment]
Hey! Good point :) I’m waiting for this feature as much as you do! Unfortunately, it’s still in the early days, and the experimental implementation is only available in Chrome behind the flag. Also, the spec itself is not stable enough to document it on MDN.

I’ll put this issue on hold until we have something more stable to document. Thanks!

**Comment by pepelsbey** [comment]
It’s now documented: https://developer.mozilla.org/en-US/docs/Web/CSS/CSS_anchor_positioning

**Comment by JustinWebDev** [comment]
Thanks!
