### ISSUE TITLE
"cancel" event for HTMLInputElement

### ISSUE THREAD

**Issue by Cipscis** [mdn/mdn#490]
### Proposal

The "cancel" event for the `HTMLInputElement`, which is fired when a picker for an input element with type "file" is cancelled without the value being changed.

This was added to the HTML standard in July 2021: [Add a "cancel" event for when file upload selection is unchanged](https://github.com/whatwg/html/pull/6735)

[HTML spec - `cancel` event](https://html.spec.whatwg.org/#event-cancel)
[HTML spec - Common `input` element APIs](https://html.spec.whatwg.org/#common-input-element-apis)

### Browser support

This feature has been supported by all modern browsers since May 2023. According to CanIUse, it currently has 83.62% global browser support. Support for this feature is already included in `mdn/browser-compat-data` and displays on the `HTMLInputElement` page.

### Tasks

- Create a page for `HTMLInputElement/cancel_event`
- Add "cancel" to the event section of the `HTMLInputElement` page, linking to the aforementioned new page

### Dependencies

No dependencies that I am aware of

### Are you willing to support this work?

I intend to draft this documentation and submit a PR, as time permits

**Comment by Cipscis** [comment]
Oh, I see this event is already documented directly against `HTMLElement`: [HTMLElement: cancel event](https://developer.mozilla.org/en-US/docs/Web/API/HTMLElement/cancel_event)

**Comment by Cipscis** [comment]
I've raised an issue with `mdn/browser-compat-data` to improve how the browser compatability data for this event is organised: https://github.com/mdn/browser-compat-data/issues/21585

**Comment by hamishwillee** [comment]
FYI normally better to create issues in mdn/content.

**Comment by Cipscis** [comment]
Thanks, I did think it was odd my issue ended up in this repo. I can't remember exactly what button on the MDN site I clicked on now that led me to the issue creation page. I'd be happy to recreate the issue over there and close this one.

**Comment by Cipscis** [comment]
Closing in favour of [new issue created on mdn/content](https://github.com/mdn/content/issues/31014)

**Comment by hamishwillee** [comment]
Thank you. It would have been fine to leave it open, but appreciate you moving it to the right place.
