### ISSUE TITLE
Add more information about the `rcap`, `rex`, `ric`, and `rch` units

### ISSUE THREAD

**Issue by francescorn** [mdn/mdn#509]
### Proposal

I propose to add more information, such as a paragraph, describing the new `rcap`, `rex`, `ric`, and `rch` units to: https://developer.mozilla.org/en-US/docs/Learn/CSS/Building_blocks/Values_and_units and https://developer.mozilla.org/en-US/docs/Web/CSS/length.

### Browser support

It is supported in Safari 17.2, Opera, Edge and Chrome.
https://developer.apple.com/documentation/safari-release-notes/safari-17_2-release-notes

WebKit commit:
https://github.com/WebKit/WebKit/commit/424dee4815091e03fcc4c9035af6e7a9a8128184

### Tasks

1. Add more information on the `rcap`, `rex`, `ric`, and `rch` units to: https://developer.mozilla.org/en-US/docs/Learn/CSS/Building_blocks/Values_and_units
2. Add more information on the `rcap`, `rex`, `ric`, and `rch` units to: https://developer.mozilla.org/en-US/docs/Web/CSS/length.

**Comment by Rumyra** [comment]
Hi @francescorn thanks for the proposal to update the docs - are you willing to do this work?

**Comment by francescorn** [comment]
Completed in: mdn/content#31901 and mdn/content#31617.

**Comment by Rumyra** [comment]
Awesome - thank you @francescorn !
