### ISSUE TITLE
Add the `cloneable` attribute to the `shadowDOM` information

### ISSUE THREAD

**Issue by francescorn** [mdn/mdn#518]
### Proposal

Support was added in STP for the `cloneable` attribute to the shadowDOM. I propose to add it to the browser-compat-data: [link](https://github.com/mdn/browser-compat-data/blob/f0fe9a91913da9c69a107bead174dceee4eede91/api/ShadowRoot.json#L406).

### Browser support

It added support in WebKit in STP 186.  [link](https://webkit.org/blog/14916/release-notes-for-safari-technology-preview-186/).
Here's an article with more information on it in WebKit.: [link](https://webkit.org/blog/13851/declarative-shadow-dom/).

### Tasks

1. Add the `cloneable` attribute to the list in browser-compat-data in: [link](https://github.com/mdn/browser-compat-data/blob/f0fe9a91913da9c69a107bead174dceee4eede91/api/ShadowRoot.json#L406)
2. Add information about experimental browsers that support the `cloneable` attribute.
3. Add information on the `cloneable` attribute to: [link](https://github.com/mdn/content/blob/main/files/en-us/web/api/web_components/using_shadow_dom/index.md)

### Are you willing to support this work?

Yes, I can do 1 and 2.

**Comment by pepelsbey** [comment]
Hey! Thank you for the proposal :) I picked it up just a bit earlier, and it’s now [merged into BCD](https://github.com/mdn/browser-compat-data/pull/21948).
