### ISSUE TITLE
Document <link rel=expect>

### ISSUE THREAD

**Issue by noamr** [mdn/mdn#524]
### Proposal

See [explainer](https://github.com/WICG/view-transitions/blob/link-proposal/document-render-blocking.md#blocking-element-id) and [HTML PR](https://github.com/whatwg/html/pull/9970)

Opening issue to document `<link rel=expect>` once it's shipped in one browser.

### Browser support

In progress

### Tasks

- [ ]

### Dependencies

- [ ]

**Comment by Rumyra** [comment]
Thanks @noamr - lmk if you're aware of a browser implementation. I can keep eyes of Firefox, but chances are this will come in Chrome earlier 👍

**Comment by noamr** [comment]
> Thanks @noamr - lmk if you're aware of a browser implementation. I can keep eyes of Firefox, but chances are this will come in Chrome earlier 👍

Yea, it's coming in Chrome M124.

**Comment by skyclouds2001** [comment]
same as https://github.com/mdn/mdn/issues/534
