### ISSUE TITLE
<link rel="expect"> render blocking

### ISSUE THREAD

**Issue by foolip** [mdn/mdn#534]
### Proposal

The `<link rel="expect">` feature allows blocking rendering until a certain element is in the DOM. It's hard to find examples or blog posts, but code snippets can be found from tests in https://wpt.fyi/results/html/dom/render-blocking?label=master&label=experimental&aligned&q=element-render-blocking

### Browser support

Supported by Chrome. (But this data isn't in BCD yet, it seems.)

### Tasks

- Add to https://developer.mozilla.org/en-US/docs/Web/HTML/Attributes/rel

### Dependencies

https://github.com/mdn/content/pull/14648, already done.

### Additional information

I'm working on adding this feature to web-features in https://github.com/web-platform-dx/web-features/pull/613

### Are you willing to support this work?

I can find a technical reviewer on the Chrome team

**Comment by noamr** [comment]
It's not supported by Safari.

**Comment by foolip** [comment]
Oh, I guess some of the tests pass for the wrong reasons?

**Comment by noamr** [comment]
> Oh, I guess some of the tests pass for the wrong reasons?

Yea there are some negative tests, in the style of "If this happens block rendering, but if that happens don't"

**Comment by jamesta696** [comment]
There isn't much real-world examples on the usage, though I've read the Chrome docs. Can someone provide some usage examples I can test using Chrome v124?

Thanks

**Comment by noamr** [comment]
> There isn't much real-world examples on the usage, though I've read the Chrome docs. Can someone provide some usage examples I can test using Chrome v124?
> 
> Thanks

I believe this is done as part of https://github.com/mdn/content/pull/32723

**Comment by jamesta696** [comment]
> > There isn't much real-world examples on the usage, though I've read the Chrome docs. Can someone provide some usage examples I can test using Chrome v124?
> > Thanks
> 
> I believe this is done as part of [mdn/content#32723](https://github.com/mdn/content/pull/32723)

Thanks, I believe Chrome 124 will be released tomorrow and I'll be able to test this fully.
Appreciate your feedback!

**Comment by skyclouds2001** [comment]
> > There isn't much real-world examples on the usage, though I've read the Chrome docs. Can someone provide some usage examples I can test using Chrome v124?
> > Thanks
> 
> I believe this is done as part of [mdn/content#32723](https://github.com/mdn/content/pull/32723)

I think the landing PR is https://github.com/mdn/content/pull/34118

**Comment by bsmth** [comment]
Are the docs here sufficient or is there anything else missing?

* https://developer.mozilla.org/en-US/docs/Web/HTML/Attributes/rel#expect
* https://developer.mozilla.org/en-US/docs/Web/API/View_Transitions_API/Using#stabilizing_page_state_to_make_cross-document_transitions_consistent

**Comment by noamr** [comment]
> Are the docs here sufficient or is there anything else missing?
> 
> * https://developer.mozilla.org/en-US/docs/Web/HTML/Attributes/rel#expect
> * https://developer.mozilla.org/en-US/docs/Web/API/View_Transitions_API/Using#stabilizing_page_state_to_make_cross-document_transitions_consistent

LGTM!

**Comment by bsmth** [comment]
Thanks a lot. I'm going to close as done for now, then. Cheers, all
