### ISSUE TITLE
Long Animation Frames

### ISSUE THREAD

**Issue by noamr** [mdn/mdn#535]
### Proposal

Add documentation for Long Animation Frames. It's already shipped in chrome, and Gecko are working on it.
Spec: https://w3c.github.io/long-animation-frames/

### Browser support

Chromium: M123: https://developer.chrome.com/blog/new-in-chrome-123#long-animation-frames
Gecko: supportive, working on it https://github.com/mozilla/standards-positions/issues/929

### Tasks

- [ ]

### Dependencies

- [ ]

**Comment by chrisdavidmills** [comment]
Thanks @noamr! This is on my worklist, so I'll get this done soon.

@Rumyra, can you assign this one to me?

**Comment by dipikabh** [comment]
Thanks to @chrisdavidmills, long animation frames is now documented: https://developer.mozilla.org/en-US/docs/Web/API/Performance_API/Long_animation_frame_timing. 🎉 

Closing this doc request as completed.
