### ISSUE TITLE
Add support for subresource integrity in imported module scripts

### ISSUE THREAD

**Issue by yoavweiss** [mdn/mdn#541]
### Proposal

SRI support for ES module imports would enable using them in documents that require SRI for certain scripts for security or privacy reasons.

See [problem statement and proposal](https://github.com/guybedford/import-maps-extensions#integrity) by @guybedford.

[HTML PR](https://github.com/whatwg/html/pull/10269)
[Chromium CL + tests](https://chromium-review.googlesource.com/c/chromium/src/+/5441822)

### Browser support

The feature is currently being prototyped in Chromium.

### Tasks

- Add an "integrity" section to https://developer.mozilla.org/en-US/docs/Web/HTML/Element/script/type/importmap
- Add an appropriate subsection to the JSON representation section

### Dependencies

- [HTML PR](https://github.com/whatwg/html/pull/10269)

### Are you willing to support this work?

Yes

**Comment by bsmth** [comment]
I think the linked PR fixes this, so I'm closing as done now. If that's a mistake, please let me know and we can reopen. Thank you!
