### ISSUE TITLE
Collaborator request for browser-compat-data

### ISSUE THREAD

**Issue by vinyldarkscratch** [mdn/mdn#55]
To whom it may concern,

I've been contributing some pretty big updates to the [`browser-compat-data`](https://github.com/mdn/browser-compat-data) repository, as well as smaller updates, particularly relating to the schema and linters for the project.  I'm really glad to be working with everyone on the repository, and being able to contribute my code to the project.  And I want to do what I can to keep the project going in the right direction.

I'm big on maintaining consistent organization, as my existing contributions have probably shown, so that, and responding to incoming issues, would be my primary focus, with additional assistance wherever I'm needed.  All of my own code will be contributed in the form of pull requests -- never directly to the repository's master branch.

I will gladly abide to the Code of Conduct, as well as the Commit Access Requirements.  I also have 2-Factor Authentication set up on my GitHub account.

Thank you for reading through, and looking forward to working with everyone!
 Vinyl

**Comment by dimitrob210** [comment]
Fix all of my problems

**Comment by Elchi3** [comment]
Hey @vinyldarkscratch, we have received this application and it is under consideration. Please be patient while we sort out the details and https://github.com/mdn/browser-compat-data/pull/3668 is approved and merged.

**Comment by vinyldarkscratch** [comment]
Not a problem, I totally understand!  I'm not going anywhere anytime soon.  :wink:

**Comment by Elchi3** [comment]
This was approved. You've been added to the list of Peers in mdn/browser-compat-data#3809 and received an invite to be a collaborator on the repo. Welcome to the team of BCD Peers!

**Comment by vinyldarkscratch** [comment]
💜

Thank you very much, happy to be on board!
