### ISSUE TITLE
Create mdn.dev repo

### ISSUE THREAD

**Issue by jwhitlock** [mdn/mdn#57]
Create a mdn.dev repository, to hold the content of https://mdn.dev.

See https://github.com/mdn/sprints/issues/922

* [x] Repo is setup (https://github.com/mdn/mdn.dev)
* [x] Collaborators added (@schalkneethling, @davidflanagan)
* [x] Has README
* [x] Has LICENSE
* [x] Has contribute.json

**Comment by schalkneethling** [comment]
I have added all three of the required files as mentioned in https://github.com/mdn/mdn/issues/57#issue-409387004

**Comment by jwhitlock** [comment]
The README is a little light. Look both ways for a bus before crossing the street.

**Comment by schalkneethling** [comment]
@jwhitlock 	Yup, will flesh it out ;)
