### ISSUE TITLE
link tabs

### ISSUE THREAD

**Issue by undersigned-dev** [mdn/mdn#573]
### Proposal

As i was reading through javascript articles i found there are multiple links in the article which opens in the same tab. As it can hinder some readers attention I thought those links opening in new tab would be great to keep the flow of reading those javascript articles 

### Tasks

<a target="_blank"> 

### Dependencies

- [ ]

### Are you willing to support this work?

this task just needs to tweak the HTML anchor tag to use "_blank" value in the target attribute

**Comment by bsmth** [comment]
Thanks for opening this one. This repo is for planning MDN content projects. Do you want to add it as a suggestion here: https://github.com/orgs/mdn/discussions/categories/platform. I'll close this for now :)
