### ISSUE TITLE
Cover `noopener-allow-popups` COOP value

### ISSUE THREAD

**Issue by yoavweiss** [mdn/mdn#579]
### Proposal

The `noopener-allow-popups` value is [being added](https://github.com/whatwg/html/pull/10394) to the `Cross-Origin-Opener-Policy` headers.

It allows origins that contain different applications with different levels of security requirements to ensure that one application cannot open another and directly script it.

We should document this header value, what it guarantees, what it doesn't, and what other steps web developers need to take in such cases.

### Browser support

Not yet. The implementation [landed](https://chromium-review.googlesource.com/c/chromium/src/+/5581251) in Chromium behind a flag, and is [ready for review](https://github.com/WebKit/WebKit/pull/30344) in WebKit.

### Tasks

- [ ]

### Dependencies

- [ ]

### Are you willing to support this work?

yes

**Comment by bsmth** [comment]
Thanks a lot, it looks like the linked PR fixes this, so I'm going to close as done.
