### ISSUE TITLE
Document how to request privileges for MDN repos

### ISSUE THREAD

**Issue by Elchi3** [mdn/mdn#6]
I think that opening an issue against this repository would be a good open process to request privileges for MDN repositories. Other proposals?

**Comment by jwhitlock** [comment]
Other possibilities:

- Open a bug on Bugzilla
- Ask on IRC
- Open an issue against the repo itself

Out of those, opening a issue (@Elchi3's original proposal) seems best to me for groups that have permissions across several repos.

I want to keep 2FA as a requirement for contributors with push access to code that runs on MDN.
