### ISSUE TITLE
Hello, the MDN SVG tutorial has not been updated for two years

### ISSUE THREAD

**Issue by BengBu-YueZhang** [mdn/mdn#60]
https://developer.mozilla.org/en-US/docs/Web/SVG/Tutorial

**Comment by jmswisher** [comment]
Lack of updates to the tutorial does not in itself mean that the content is out of date. However, if you are aware of information in the tutorial that is inaccurate, you can either:
- Update it yourself, if you know the correct information. (MDN is a wiki.)
- Submit an issue in https://github.com/mdn/sprints/issues which is where the MDN staff team tracks work to be done.
