### ISSUE TITLE
Capture ajax requests in HTTP Response parser

### ISSUE THREAD

**Issue by Toniiiio** [mdn/mdn#602]
### Proposal

The current implementation of HTTP Response parser only captures the main page (index.html) and not the ajax requests if i am not mistkane. Would that also be possible to capture the ajax requests?

### Browser support

Firefox

### Tasks

- [ ]

### Dependencies

- [ ]

### Are you willing to support this work?

Yes

**Comment by bsmth** [comment]
Thanks for opening. Are you referring to Firefox implementation? We're tracking documentation for web technologies in this repo, not software bugs. It's better to [check support](https://support.mozilla.org/en-US/questions/firefox) where you can ask questions. I'm going to close for now, but you can reply if you think I've made a mistake. Thanks.
