### ISSUE TITLE
如何打包出离线版本的MDN文档？

### ISSUE THREAD

**Issue by k2522887** [mdn/mdn#609]
### Proposal

如何打包出离线版本的MDN文档？
我尝试了好久，都没有打包出离线官方网站。

### Browser support

Chrome

### Tasks

- [ ]

### Dependencies

- [ ]

### Additional information

请帮助我打包出离线网站谢谢，或者给我打包好的也可以

**Comment by k2522887** [comment]
我们需要不联网开发网页，公司要求是不联网的，前端开发少了MDN就少了灵魂

**Comment by skyclouds2001** [comment]
自己本地克隆个仓库再构建运行就行

**Comment by k2522887** [comment]
起不来呀 有没有中文构建流程呢？我翻译文档打包出来了，后面启动项目都不行了

在 2024-12-17 02:43:23，skyclouds2001 ***@***.***> 写道：


自己本地克隆个仓库再构建运行就行

**Comment by skyclouds2001** [comment]
英文就是 https://github.com/mdn/content，其他语言的翻译就是 https://github.com/mdn/translated-content

**Comment by k2522887** [comment]
你说的链接，我已经打包出来了，我也可以给你一份。
下面的链接，这个网站，启动不起来。
https://github.com/mdn/yari

下载yarn但是启动不成功。
要不直接给我打包好的部署包吧，中文和英文的网站就行啊，非常感谢！

在 2024-12-17 23:15:56，skyclouds2001 ***@***.***> 写道：


英文就是 https://github.com/mdn/content，其他语言的翻译就是https://github.com/mdn/translated-content

**Comment by skyclouds2001** [comment]
是不是 https://github.com/mdn/yari/blob/main/.env-dist 没按照 https://github.com/mdn/yari/blob/abad97728fbcd3a59808d60e7af5018bd3d882f1/README.md?plain=1#L47-L49 说的改

**Comment by bsmth** [comment]
Thanks, both. I'm going to close this issue so that it's not triaged as a proposal, but feel free to continue the discussion / reply here. You're also welcome to join https://mdn.dev/discord if you'd like to chat :)

**Comment by skyclouds2001** [comment]
另外给个建议，下次提问时候最好使用英文
