### ISSUE TITLE
tmui tag is displayed as-is on the Participating_in_the_Mozilla_project page

### ISSUE THREAD

**Issue by moijes12** [mdn/mdn#61]
This issue was observed on page https://developer.mozilla.org/en-US/docs/Mozilla/Participating_in_the_Mozilla_project on a Mozilla Developer Edition 66.0b14 (64-bit).

Below is what I see on the above page

![image](https://user-images.githubusercontent.com/4566851/54184711-4bab1b00-44cd-11e9-80eb-6207fbf75a03.png)
 
I am not sure about the usage of tmui. Is this a valid html tag ?

**Comment by jwhitlock** [comment]
Issue moved to [mdn/sprints #1174](https://github.com/mdn/sprints/issues/1174) via [**ZenHub**](https://www.zenhub.com/)
