### ISSUE TITLE
Document the JavaScript self-profiling API

### ISSUE THREAD

**Issue by captainbrosset** [mdn/mdn#610]
### Proposal

The JS Self-Profiling API's draft spec is here: https://wicg.github.io/js-self-profiling/
This API can be used by web developers to perform profiling, at runtime, to gain performance insights about their production webapps.

The feature is already known to BCD, see https://github.com/mdn/browser-compat-data/blob/main/api/Profiler.json

### Browser support

Supported on Chrome, Chrome Android, and Edge, since version 94. See https://web-platform-dx.github.io/web-features-explorer/features/profiler/

### Tasks

- [ ] The `Profiler` API needs to be documented

**Comment by skyclouds2001** [comment]
this is duplicate with https://github.com/mdn/mdn/issues/507

**Comment by bsmth** [comment]
Thanks, all. I'm closing this one in favor of 507 linked above as it's been opened first.
