### ISSUE TITLE
Application to be a peer on mdn/browser-compat-data

### ISSUE THREAD

**Issue by jpmedley** [mdn/mdn#63]
I have read, and agree to abide by, the Mozilla Commit Access Requirements.

**Comment by Elchi3** [comment]
Hey @jpmedley, we have received this application and it is under consideration. Please be patient while we sort out the details and https://github.com/mdn/browser-compat-data/pull/3668 is approved and merged.

**Comment by Elchi3** [comment]
This was approved. You've been added to the list of Peers in https://github.com/mdn/browser-compat-data/pull/3797 and received an invite to be a collaborator on the repo. Welcome to the team of BCD Peers!
