### ISSUE TITLE
Remove jwhitlock from organization owners

### ISSUE THREAD

**Issue by jwhitlock** [mdn/mdn#66]
I've leaving the MDN team, so it is inappropriate for me to continue to be an organization owner. That would leave 3 owners, which could be a healthy number, but no one from the dev team. If you need another owner, I suggest @escattone (for seniority) and / or @peterbe (for experience with managing multiple Mozilla repos).

Some of my unfinished work may be relevant:

* I came up with a system for categorizing projects by their security demands in [Roles and teams in the MDN organization](https://github.com/mdn/mdn/blob/master/roles_and_teams.md). My next step was to add a "Tier 1", "Tier 2", and "Tier 3" tag to all the repos, but since I didn't, it is fuzzy which repos require stricter reviews. Org Owners also get Owner on all the repos, which is a consideration for replacing me.
* I wanted to add an "Emeritus Members" doc, to list people previously involved. It should have been fast, but I was hoping to get years of service in the doc too, so I procrastinated. If I'd done that, there would be a natural place to put my name, and a way to transition people from active to inactive status.
* I felt the Member list was too broad to justify moving https://github.com/mozilla/kuma into the MDN org, so I delayed that as well. The new dev team may decide it is time to move it in. I think the private repos should remain in the Mozilla org, to avoid converting the MDN org into a paying account.

**Comment by peterbe** [comment]
Note-to-self; These are the 15 members of `mozilla/mdn`
https://github.com/orgs/mozilla/teams/mdn/members
They're all Mozilla staff, and from what I can see, they're all still members of staff at Mozilla. 

There are plenty admins that I very much doubt needs to be admin: https://github.com/mozilla/kuma/settings/collaboration Can we revoke those?

I'd be much in favor of moving `mozilla/kuma` to the `mdn` org. What's involved with things like docker, jenkins, etc. I think GitHub does a bunch of good work setting up automatic redirects.

**Comment by ExE-Boss** [comment]
I&nbsp;agree, we&nbsp;should move `mozilla/kuma` to&nbsp;the&nbsp;@mdn organisation.

**Comment by Elchi3** [comment]
I removed @jwhitlock as an owner of the mdn org. @escattone is a new owner. (also, I removed several outdated memberships and teams)

For the other issues, please open new issues if you feel strong about them. I agree the move of kuma would be nice, but please track separately also.
