### ISSUE TITLE
Transfer in @ExE-Boss/mdn-packages as @mdn/packages and publish @mdn/prettier-config

### ISSUE THREAD

**Issue by ExE-Boss** [mdn/mdn#67]
I have created **[@ExE-Boss/mdn-packages](https://github.com/ExE-Boss/mdn-packages)** which contains miscellaneous **MDN** packages, like **@mdn/prettier-config** or a shared lint script, like what I suggested in https://github.com/mdn/data/pull/362.

needinfo?(@Elchi3)

**Comment by Elchi3** [comment]
Thanks for your work! I don't think we're ready to transfer this. 

I think this assumes we're going with prettier, eslint config, pnpm and possibly other things. All these need separate ADRs and MDN team decisions if and how we want to use them. 

For prettier, I think @schalkneethling wanted to look into it as well.

There are at least two steps we need to do before transferring this or going into any direction here:

1) File separate ADRs, discuss, and document decisions.
2) Decide how to organize all things that we've agreed to from the ADR discussions. (maybe all the agreed things go into "mdn-packages", maybe there are other options.)
