### ISSUE TITLE
The Message​Channel demo page 404

### ISSUE THREAD

**Issue by Jack-rainbow** [mdn/mdn#68]
`API-URL:`
___
https://developer.mozilla.org/zh-CN/docs/Web/API/MessageChannel

`DEMO-404-URL:`
___
http://mdn.github.io/channel-messaging-basic-demo/

`What is Expected?`
___
Can I restore the demo address to help me improve my learning API?

Thank you.

**Comment by chrisdavidmills** [comment]
This demo got moved, so the links in the chinese page ended up broken. I've fixed them now.

Thanks for letting us know!
