### ISSUE TITLE
Create template contribute.json

### ISSUE THREAD

**Issue by jwhitlock** [mdn/mdn#7]
Create a file like ``contribute.dist.json`` that contains the common settings for [contribute.json](https://www.contributejson.org) for our MDN sample code projects.

**Comment by a2sheppy** [comment]
I'm working on this (I have the JSON done, or close to it). Should an explanation of what to do with this file when adding it to a new sample go in README.md or should we have a CONTRIBUTE.md that explains how to add and update samples?

**Comment by jwhitlock** [comment]
Fix in #12 - thanks!
