### ISSUE TITLE
Collaborator access request for mdn/browser‑compat‑data

### ISSUE THREAD

**Issue by ExE-Boss** [mdn/mdn#70]
I’ve&nbsp;been contributing to&nbsp;[mdn/browser‑compat‑data](https://github.com/mdn/browser-compat-data) since the&nbsp;**26<sup>th</sup>&nbsp;of&nbsp;February&nbsp;2018**, which more or&nbsp;less makes me&nbsp;one of&nbsp;the&nbsp;longest, most&nbsp;active non‑Mozilla contributors to&nbsp;the&nbsp;project.

I’ve&nbsp;recently mainly been contributing&nbsp;linter and&nbsp;infrastructure improvements and&nbsp;reviewing&nbsp;PRs made&nbsp;by&nbsp;other contributors.

Having collaborator access would make it&nbsp;easier and&nbsp;faster for&nbsp;me&nbsp;to&nbsp;handle correct label assignment for&nbsp;my&nbsp;PRs without needing to&nbsp;ping&nbsp;BCD&nbsp;peers to&nbsp;do&nbsp;it&nbsp;for&nbsp;me.<br/> (**case&nbsp;in&nbsp;point**:&nbsp;https://github.com/mdn/browser-compat-data/pull/3913#issuecomment-484182418, https://github.com/mdn/browser-compat-data/pull/3987, https://github.com/mdn/browser-compat-data/pull/3445, etc…).

---

I&nbsp;have read and&nbsp;agree to&nbsp;abide by&nbsp;the&nbsp;[Code&nbsp;of&nbsp;conduct](https://github.com/mdn/mdn/blob/master/CODE_OF_CONDUCT.md) and&nbsp;Mozilla’s&nbsp;[Commit&nbsp;Access&nbsp;Requirements](https://www.mozilla.org/en-US/about/governance/policies/commit/requirements/).

I&nbsp;also have 2FA&nbsp;enabled on&nbsp;my&nbsp;GitHub account.

---

/cc @Elchi3

**Comment by Elchi3** [comment]
Hey @ExE-Boss,

we really appreciate the code and data contributions you've made to date; you've done some great work in the MDN community.

There are other responsibilities of being a [Peer](https://github.com/mdn/browser-compat-data/blob/master/governance.md#peers) that we'd like to see a bit more evidence of from you, such as making other contributors feel welcome and appreciated, paying more attention to the overall project goals and strategy, and being clearer in PRs what your motivation for a change is, how your additions work, and what you've done.

Once we've seen an improvement from you in these areas in the future, we'd be happy to reconsider your application. Feel free to reach out to me privately if you want to get more examples, ask for further advice, or anything else.

Thanks,
Florian on behalf of the MDN team
