### ISSUE TITLE
Broken IntersectionObserver example

### ISSUE THREAD

**Issue by perry-mitchell** [mdn/mdn#76]
The simple example down the bottom of the page (for the IntersectionObserver API) is broken, and doesn't work when scrolling: https://developer.mozilla.org/en-US/docs/Web/API/Intersection_Observer_API

The issue is because of invalid JS in the example: `Uncaught SyntaxError: Malformed arrow function parameter list`

I'm quite comfortable editing MDN pages to provide fixes, but I'm not sure as to what the procedure is with updating codepen examples - I can't see where the reference to the actual codepen is: `{{EmbedLiveSample('A_simple_example', 400, 400)}}` - If I could link my fixed codepen for the example I'd submit that, but I don't understand how it works.

**Comment by wbamberg** [comment]
Thanks for filing, Perry!

The example works by slurping up all the code blocks under the "A simple example" heading in the page (https://developer.mozilla.org/en-US/docs/Web/API/Intersection_Observer_API#A_simple_example) and embedding them in an iframe. So If you find the code block with the error, fix it just by editing the page, then maybe shift-refresh the page, it ought to work.

(I guess it is this bit?

```js
buildThresholdList() => {
  let thresholds = [];
  let numSteps = 20;

  for (let i=1.0; i<=numSteps; i++) {
    let ratio = i/numSteps;
    thresholds.push(ratio);
  }

  thresholds.push(0);
  return thresholds;
}
```

?)

**Comment by perry-mitchell** [comment]
Yes @wbamberg, that's the bit :)

Unfortunately I don't have time right now to address this anymore, but I appreciate the guidance for the next time I find such an issue. MDN is a staple for me!

**Comment by wbamberg** [comment]
@perry-mitchell , thanks for the update (and for reporting this issue in the first place). I've fixed the example.

I guess I don't have rights to close issues in this repo though 🤷.

**Comment by perry-mitchell** [comment]
Thanks @wbamberg! Much appreciated :)
