### ISSUE TITLE
Blank doc for grid-column

### ISSUE THREAD

**Issue by samuelpetroline** [mdn/mdn#78]
The entry doc for the brazilian [grid-column page](https://developer.mozilla.org/pt-BR/docs/Web/CSS/grid-column) is blank

Has it moved or something like that?

**Comment by chrisdavidmills** [comment]
The paghe content doesn't look like it was ever written. Do you fancy helping us to write a translation? ;-)

**Comment by samuelpetroline** [comment]
Sure! Will be happy to do so. How can I edit the page, though?

**Comment by chrisdavidmills** [comment]
To edit MDN, you need to have an MDN login; our logins are done using GitHub auth, so you need a GitHub account too.

Once you've logged in, you need to press the "Edit in Wiki" button, then on the next page that appears, press the "Edit" button. You'll then get a WYSIWYG edit that you can use to edit the page content.
