### ISSUE TITLE
link 404

### ISSUE THREAD

**Issue by xiaoCong2014** [mdn/mdn#79]
This link( [https://developer.mozilla.org/zh-CN/Learn/Understanding_URLs](https://developer.mozilla.org/zh-CN/Learn/Understanding_URLs) ) is 404, in this page ( [https://developer.mozilla.org/zh-CN/docs/Glossary/URL](https://developer.mozilla.org/zh-CN/docs/Glossary/URL) ).

**Comment by chrisdavidmills** [comment]
Thannk you for reporting this. I have changed it to the correct URL.
