### ISSUE TITLE
Have example code repos licensed as CC0

### ISSUE THREAD

**Issue by teoli2003** [mdn/mdn#8]
Hi!

I've seen CC0 license, as well as MPL-2.0

I think we should have all of them in CC0, and also indicate this in the contribution.md

**Comment by Elchi3** [comment]
Remaining repos with no license or MPL2 that should likely be CC0:

- [ ] https://github.com/mdn/addon-sdk-content-scripts
- [ ] https://github.com/mdn/advanced-js-fundamentals-ck
- [ ] https://github.com/mdn/beginning-programming-content-kit
- [ ] https://github.com/mdn/crossbrowser-testing-lab
- [ ] https://github.com/mdn/data
- [ ] https://github.com/mdn/e10s-example-addons
- [ ] https://github.com/mdn/performance-scenarios
- [ ] https://github.com/mdn/repl-panel
- [ ] https://github.com/mdn/webextensions-examples

**Comment by Elchi3** [comment]
CC'ing @wbamberg and @chrisdavidmills to look into the remaining ones. I'm taking care of https://github.com/mdn/data

**Comment by wbamberg** [comment]
https://github.com/mdn/e10s-example-addons/pull/2
https://github.com/mdn/performance-scenarios/pull/1
https://github.com/mdn/repl-panel/pull/5
https://github.com/mdn/addon-sdk-content-scripts/pull/8

I'm not sure what to do about webextensions-examples. I think it might be hard to get an explicit answer from all the contributors. I'd be inclined to leave it as is. Note that it doesn't contain data or any content intended to be embedded in documentation. They really are standalone examples.

**Comment by chrisdavidmills** [comment]
I've done the crossbrowser-testing-lab and beginning-programming-content-kit; the data and advanced-js-fundamentals-ck suffer from the same problem Will cited above, so again I think we should just leave them unless we have a good reason not to.

**Comment by Elchi3** [comment]
Thanks Will and Chris! I agree, so let's close this issue then.
