### ISSUE TITLE
Incorrect example description for min()

### ISSUE THREAD

**Issue by HandsomeMedia** [mdn/mdn#91]
In the first block beneath the opening example here:
https://developer.mozilla.org/en-US/docs/Web/CSS/min

the copy reads:
> ...but will be smaller if the viewport is less than 1000px wide.

Shouldn't that be "less than 400px wide"?

**Comment by chrisdavidmills** [comment]
Yeah, I think you're right here. I've updated the text and added a brief explanation in parens. Thanks for reporting this!
