### ISSUE TITLE
MDN page link leads to porn site

### ISSUE THREAD

**Issue by JoseAMijaresRS** [mdn/mdn#96]
Sorry to say that today I discovered that in this MDN website page:
[https://developer.mozilla.org/es/docs/Web/HTTP/Access_control_CORS](https://developer.mozilla.org/es/docs/Web/HTTP/Access_control_CORS)

In the part refering to CORS usage related to fonts, specifically in this paragraph:
"Fuentes Web (para usos de fuente en dominios cruzados @font-face dentro de CSS), para que los servidores puedan mostrar fuentes TrueType que sólo puedan ser cargadas por sitios cruzados y usadas por sitios web que lo tengan permitido."
The link leads to a nasty porn site: `http://www.webfonts.info_` (peterbe, Mar 2021: I obfuscated and turn it into preformatted text instead of a real link so people don't accidentally click on it. It's NSFW!)

Please find the original legitimate link and change it.
let me know when done please

**Comment by wbamberg** [comment]
Thanks for filing!

The en-US version of this page links to https://www.w3.org/TR/css-fonts-3/#font-fetching-requirements , and I have updated the es version accordingly: https://wiki.developer.mozilla.org/es/docs/Web/HTTP/Access_control_CORS. Please confirm that it looks fixed to you. (I've sent you the "wiki.developer.mozilla.org" version, since the "developer.mozilla.org" typically lags a bit).

**Comment by TheDynamicPunk** [comment]
Yeah it looks alright to me now. Issue seems to be fixed!

**Comment by JoseAMijaresRS** [comment]
Yep
    
    
    El 03/10/2020 a las 12:57 p. m.,
      Ashutosh escribió:
    
    
      
      Yeah it looks alright to me now. Issue seems to be fixed!
      —
        You are receiving this because you authored the thread.
        Reply to this email directly, view it on GitHub, or unsubscribe.
      [
{
"@context": "http://schema.org",
"@type": "EmailMessage",
"potentialAction": {
"@type": "ViewAction",
"target": "https://github.com/mdn/mdn/issues/96#issuecomment-703140890",
"url": "https://github.com/mdn/mdn/issues/96#issuecomment-703140890",
"name": "View Issue"
},
"description": "View this Issue on GitHub",
"publisher": {
"@type": "Organization",
"name": "GitHub",
"url": "https://github.com"
}
}
]
    
   
	
      
		Libre de virus. www.avast.com

**Comment by sohamsshah** [comment]
@JoseAMijaresRS Thanks for reporting this. This is incredible work for the community.
